services:
  dozzle:
    image: amir20/dozzle:latest
    command: agent
    environment:
      DOZZLE_HOSTNAME: tana
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 5s
      retries: 5
      start_period: 5s
      start_interval: 5s
    ports:
      - 7007:7007/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  ffmpeg-webhook:
    build:
      context: ./ffmpeg-webhook/
      dockerfile: ./Dockerfile
    labels:
      traefik.http.routers.ffmpeg-webhook-router.entrypoints: websecure
      traefik.http.routers.ffmpeg-webhook-router.rule: Host(`ffmpeg-webhook.bob.house`)
      traefik.http.routers.ffmpeg-webhook-router.tls: "true"
      traefik.http.services.ffmpeg-webhook-service.loadbalancer.server.port: "9000"
    volumes:
      - /mnt/md1/youtube/:/videos/:rw

  glances:
    image: nicolargo/glances:latest
    environment:
      GLANCES_OPT: -w
    labels:
      traefik.http.routers.glances-router.entrypoints: websecure
      traefik.http.routers.glances-router.rule: Host(`glances-tana.bob.house`)
      traefik.http.routers.glances-router.tls: "true"
      traefik.http.services.glances-service.loadbalancer.server.port: "61208"
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro

  gluetun:
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      TZ: Etc/UTC
      UPDATER_PERIOD: 24h
    env_file:
      - ~/Configurations/gluetun.env
    labels:
      traefik.http.routers.qbittorrent-router.entrypoints: websecure
      traefik.http.routers.qbittorrent-router.rule: Host(`qbittorrent.bob.house`)
      traefik.http.routers.qbittorrent-router.tls: "true"
      traefik.http.services.qbittorrent-service.loadbalancer.server.port: "8080"
    ports:
      - 6881:6881/tcp # qbittorrent
      - 6881:6881/udp

  jellyfin:
    image: jellyfin/jellyfin:latest
    devices:
      - /dev/dri:/dev/dri
    healthcheck:
      test: curl -f http://localhost:8096/health
    labels:
      traefik.http.routers.jellyfin-router.entrypoints: websecure
      traefik.http.routers.jellyfin-router.rule: Host(`jellyfin.bob.house`)
      traefik.http.routers.jellyfin-router.tls: "true"
      traefik.http.services.jellyfin-service.loadbalancer.server.port: "8096"
    volumes:
      - ~/.jellyfin/config/:/config/:rw
      - ~/.jellyfin/cache/:/cache/:rw
      - /mnt/md1/anime/:/media/anime/:rw
      - /mnt/md1/films/:/media/films/:rw
      - /mnt/md1/streamers/:/media/streamers/:rw
      - /mnt/md0/tvshows/:/media/tv/:rw
      - /mnt/md1/videos/:/media/videos/:rw
      - /mnt/md1/music/:/media/music/:rw
      - /mnt/md1/pictures/:/media/pictures/:rw
      - /mnt/md1/youtube/:/media/youtube/:rw

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    environment:
      LOG_LEVEL: debug
      TZ: UTC
    labels:
      traefik.http.routers.jellyseerr-router.entrypoints: websecure
      traefik.http.routers.jellyseerr-router.rule: Host(`jellyseerr.bob.house`)
      traefik.http.routers.jellyseerr-router.tls: "true"
      traefik.http.services.jellyseerr-service.loadbalancer.server.port: "5055"
    volumes:
      - ~/.jellyseerr/:/app/config/:rw

  kopia:
    image: kopia/kopia:latest
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --insecure
      - --address=0.0.0.0:51515
      - --server-username=a72691ffb1328c15
      - --server-password=54b2ffddfbb10d02b59a5c2b8f9149ff
    env_file:
      - ~/Configurations/kopia.env
    labels:
      traefik.http.routers.kopia-router.entrypoints: websecure
      traefik.http.routers.kopia-router.rule: Host(`kopia-tana.bob.house`)
      traefik.http.routers.kopia-router.tls: "true"
      traefik.http.services.kopia-service.loadbalancer.server.port: "51515"
    volumes:
      # Mount local folders needed by kopia
      - ~/.kopia/config/:/app/config/:rw
      - ~/.kopia/cache/:/app/cache/:rw
      - ~/.kopia/logs/:/app/logs/:rw
      # Mount local folders to snapshot
      - ~/:/data/:ro
      # Mount repository location
      - /repository/:/repository/:rw

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    environment:
      PGID: "0"
      PUID: "0"
      TZ: Etc/UTC
    labels:
      traefik.http.routers.lidarr-router.entrypoints: websecure
      traefik.http.routers.lidarr-router.rule: Host(`lidarr.bob.house`)
      traefik.http.routers.lidarr-router.tls: "true"
      traefik.http.services.lidarr-service.loadbalancer.server.port: "8686"
    volumes:
      - ~/.lidarr/:/config/:rw
      - /mnt/md1/downloads/:/config/Downloads/complete/:rw
      - /mnt/md1/music/:/music/:rw

  mediamtx:
    image: bluenviron/mediamtx:latest
    environment:
      MTX_RTSPTRANSPORTS: tcp
      WEBRTCADDITIONALHOSTS: 192.168.1.70
    ports:
      - 8554:8554/tcp # rtsp

  metube:
    image: ghcr.io/alexta69/metube:latest
    environment:
      OUTPUT_TEMPLATE: '%(playlist_title&Playlist |)S%(playlist_title|)S%(playlist_uploader& by |)S%(playlist_uploader|)S%(playlist_autonumber& - |)S%(playlist_autonumber|)S%(playlist_count& of |)S%(playlist_count|)S%(playlist_autonumber& - |)S%(uploader,creator|UNKNOWN_AUTHOR)S %(release_date>%Y-%m-%d,upload_date>%Y-%m-%d|UNKNOWN_DATE)S - %(title|UNKNOWN_TITLE)S [%(id)s].%(ext)s'
      OUTPUT_TEMPLATE_PLAYLIST: '%(playlist_title&Playlist |)S%(playlist_title|)S%(playlist_uploader& by |)S%(playlist_uploader|)S%(playlist_autonumber& - |)S%(playlist_autonumber|)S%(playlist_count& of |)S%(playlist_count|)S%(playlist_autonumber& - |)S%(uploader,creator|UNKNOWN_AUTHOR)S %(release_date>%Y-%m-%d,upload_date>%Y-%m-%d|UNKNOWN_DATE)S - %(title|UNKNOWN_TITLE)S [%(id)s].%(ext)s'
      STATE_DIR: /data/state/
      TEMP_DIR: /data/temp/
      YTDL_OPTIONS: '{"cookiefile":"/cookies/cookies.txt","writesubtitles":true,"subtitleslangs":["en","-live_chat"],"updatetime":false,"postprocessors":[{"key":"Exec","exec_cmd":"chmod 0664","when":"after_move"},{"key":"FFmpegEmbedSubtitle","already_have_subtitle":false},{"key":"FFmpegMetadata","add_chapters":true}]}'
    labels:
      traefik.http.routers.metube-router.entrypoints: websecure
      traefik.http.routers.metube-router.rule: Host(`metube.bob.house`)
      traefik.http.routers.metube-router.tls: "true"
      traefik.http.services.metube-service.loadbalancer.server.port: "8081"
    volumes:
      - ~/.metube/:/data/:rw
      - ~/cookies.txt:/cookies/cookies.txt:ro
      - /mnt/md1/youtube/:/downloads/:rw

  navidrome:
    image: deluan/navidrome:latest
    environment:
      ND_BASEURL: ""
      ND_ENABLEINSIGHTSCOLLECTOR: "false"
      ND_LOGLEVEL: info
      ND_SCANSCHEDULE: 1h
      ND_SESSIONTIMEOUT: 24h
    labels:
      traefik.http.routers.navidrome-router.entrypoints: websecure
      traefik.http.routers.navidrome-router.rule: Host(`navidrome.bob.house`)
      traefik.http.routers.navidrome-router.tls: "true"
      traefik.http.services.navidrome-service.loadbalancer.server.port: "4533"
    volumes:
      - ~/.navidrome/:/data/:rw
      - /mnt/md1/music/:/music/:ro

  nodered:
    image: nodered/node-red:latest
    env_file:
      - ~/Configurations/nodered.env
    environment:
      NODE_RED_DISABLE_TELEMETRY: "true"
      TZ: Etc/UTC
    labels:
      traefik.http.routers.nodered-router.entrypoints: websecure
      traefik.http.routers.nodered-router.rule: Host(`nodered.bob.house`)
      traefik.http.routers.nodered-router.tls: "true"
      traefik.http.services.nodered-service.loadbalancer.server.port: "1880"
    volumes:
      - ~/.nodered/:/data/:rw
      - /mnt/md1/youtube/:/youtube/:rw

  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    environment:
      TZ: Etc\UTC
    labels:
      traefik.http.routers.pinchflat-router.entrypoints: websecure
      traefik.http.routers.pinchflat-router.rule: Host(`pinchflat.bob.house`)
      traefik.http.routers.pinchflat-router.tls: "true"
      traefik.http.services.pinchflat-service.loadbalancer.server.port: "8945"
    volumes:
      - ~/.pinchflat/config/:/config/:rw
      - /mnt/md1/downloads/pinchflat/:/downloads/:rw
      - ~/cookies.txt:/config/extras/cookies.txt:rw

  portainer:
    image: portainer/agent:latest
    ports:
      - 9001:9001/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /var/lib/docker/volumes/:/var/lib/docker/volumes/:rw
      - /:/host/:rw

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Etc/UTC
    labels:
      traefik.http.routers.prowlarr-router.entrypoints: websecure
      traefik.http.routers.prowlarr-router.rule: Host(`prowlarr.bob.house`)
      traefik.http.routers.prowlarr-router.tls: "true"
      traefik.http.services.prowlarr-service.loadbalancer.server.port: "9696"
    volumes:
      - ~/.prowlarr/:/config/:rw

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Etc/UTC
      WEBUI_PORT: "8080"
      TORRENTING_PORT: "6881"
    network_mode: service:gluetun
    volumes:
      - ~/.qbittorrent/:/config/:rw
      - /mnt/md1/downloads/:/downloads/:rw

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      PGID: "0"
      PUID: "0"
      TZ: Etc/UTC
    labels:
      traefik.http.routers.radarr-router.entrypoints: websecure
      traefik.http.routers.radarr-router.rule: Host(`radarr.bob.house`)
      traefik.http.routers.radarr-router.tls: "true"
      traefik.http.services.radarr-service.loadbalancer.server.port: "7878"
    volumes:
      - ~/.radarr/:/config/:rw
      - /mnt/md1/downloads/:/config/Downloads/complete/:rw
      - /mnt/md1/films/:/movies/:rw

  real-time-streaming:
    build:
      context: ./real-time-streaming/
      dockerfile: ./Dockerfile
    depends_on:
      mediamtx:
        condition: service_started
    volumes:
      - /mnt/md1/youtube/:/videos/:ro

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    environment:
      HAS_IPV6: "false"
      PGID: "0"
      PUID: "0"
      TZ: Etc/UTC
    labels:
      traefik.http.routers.sabnzbd-router.entrypoints: websecure
      traefik.http.routers.sabnzbd-router.rule: Host(`sabnzbd.bob.house`)
      traefik.http.routers.sabnzbd-router.tls: "true"
      traefik.http.services.sabnzbd-service.loadbalancer.server.port: "8080"
    volumes:
      - ~/.sabnzbd/:/config/:rw
      - /mnt/md1/downloads/:/config/Downloads/complete/:rw
      - /mnt/md1/downloads/incomplete/:/config/Downloads/incomplete/:rw

  sickgear:
    image: sickgear/sickgear:latest
    labels:
      traefik.http.routers.sickgear-router.entrypoints: websecure
      traefik.http.routers.sickgear-router.rule: Host(`sickgear.bob.house`)
      traefik.http.routers.sickgear-router.tls: "true"
      traefik.http.services.sickgear-service.loadbalancer.server.port: "8081"
    volumes:
      - ~/.sickgear/config/:/config/:rw
      - ~/.sickgear/data/:/data/:rw
      - /mnt/md0/tvshows/:/tv/:rw
      - /mnt/md1/anime/:/anime/:rw
      - /mnt/md1/downloads/:/downloads/:rw
      - /mnt/md1/incoming/:/incoming/:rw
      - /mnt/md1/films/:/films/:rw
      - /mnt/md1/music/:/music/:rw
      - /mnt/md1/pictures/:/pictures/:rw
      - /mnt/md1/videos/:/videos/:rw

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      PGID: "0"
      PUID: "0"
      TZ: Etc/UTC
    labels:
      traefik.http.routers.sonarr-router.entrypoints: websecure
      traefik.http.routers.sonarr-router.rule: Host(`sonarr.bob.house`)
      traefik.http.routers.sonarr-router.tls: "true"
      traefik.http.services.sonarr-service.loadbalancer.server.port: "8989"
    volumes:
      - ~/.sonarr/:/config/:rw
      - /mnt/md0/tvshows/:/data/media/tvshows/:rw
      - /mnt/md1/downloads/:/config/Downloads/complete/:rw

  traefik:
    image: traefik:latest
    command:
      # - --accesslog=true
      - --api.insecure=true
      - --certificatesresolvers.cloudflare.acme.dnsChallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      - --certificatesresolvers.cloudflare.acme.email=mail@bob.codes
      - --certificatesresolvers.cloudflare.acme.storage=/var/certs/acme.json
      - --entrypoints.websecure.address=:443
      # TRACE  DEBUG  INFO  WARN  ERROR  FATAL  PANIC
      - --log.level=INFO
      - --metrics.prometheus=true
      - --metrics.prometheus.addentrypointslabels=true
      - --metrics.prometheus.addrouterslabels=true
      - --metrics.prometheus.addserviceslabels=true
      - --providers.docker
    env_file:
      - ~/Configurations/traefik.env
    labels:
      traefik.http.routers.traefik-router.entrypoints: websecure
      traefik.http.routers.traefik-router.rule: Host(`traefik-tana.bob.house`)
      traefik.http.routers.traefik-router.tls: "true"
      traefik.http.routers.traefik-router.tls.certresolver: cloudflare
      traefik.http.routers.traefik-router.tls.domains[0].main: bob.house
      traefik.http.routers.traefik-router.tls.domains[0].sans: '*.bob.house'
      traefik.http.services.traefik-service.loadbalancer.server.port: "8080"
    networks:
      default:
        ipv4_address: 172.18.0.2
    ports:
      - 443:443/tcp
    volumes:
      - certificates-volume:/var/certs/:rw
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  tunarr:
    image: ghcr.io/chrisbenincasa/tunarr:latest-vaapi
    devices:
      - /dev/dri:/dev/dri:rwm
    environment:
      LOG_LEVEL: INFO
      TZ: Etc/UTC
    labels:
      traefik.http.routers.tunarr-router.entrypoints: websecure
      traefik.http.routers.tunarr-router.rule: Host(`tunarr.bob.house`)
      traefik.http.routers.tunarr-router.tls: "true"
      traefik.http.services.tunarr-service.loadbalancer.server.port: "8000"
    volumes:
      - ~/.tunarr/:/config/tunarr/:rw
      - /mnt/md1/anime/:/media/anime/:ro
      - /mnt/md1/films/:/media/films/:ro
      - /mnt/md1/streamers/:/media/streamers/:ro
      - /mnt/md0/tvshows/:/media/tv/:ro
      - /mnt/md1/videos/:/media/videos/:ro
      - /mnt/md1/music/:/media/music/:ro
      - /mnt/md1/pictures/:/media/pictures/:ro
      - /mnt/md1/youtube/:/media/youtube/:ro

  windows-tana:
    image: dockurr/windows:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/kvm:/dev/kvm:rwm
      - /dev/net/tun:/dev/net/tun:rwm
    env_file:
      - ~/Configurations/windows-tana.env
    environment:
      VERSION: "2022"
      CPU_CORES: "4"
      DISK_SIZE: 64G
      RAM_SIZE: 8G
      REGION: en-GB
      KEYBOARD: en-GB
      USERNAME: bob
    labels:
      traefik.http.routers.windows-tana-router.entrypoints: websecure
      traefik.http.routers.windows-tana-router.rule: Host(`windows-tana.bob.house`)
      traefik.http.routers.windows-tana-router.tls: "true"
      traefik.http.services.windows-tana-service.loadbalancer.server.port: "8006"
    ports:
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m0s
    volumes:
      - ~/.windows/:/storage/:rw
      - /mnt/md1/:/data/:rw

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          ip_range: 172.18.5.0/24

volumes:
  certificates-volume:
