- id: toggle_christmas_lights
  alias: "Toggle Christmas Lights"
  triggers:
    - trigger: time
      at: sensor.sun_next_dawn
    - trigger: time
      at: "09:00:00"
    - trigger: time
      at: sensor.sun_next_dusk
    - trigger: time
      at: "00:00:00"
  conditions: []
  actions:
    - action: light.toggle
      metadata: {}
      target:
        entity_id: light.l930_10
      data:
        transition: 60
- id: bedroom_light_on
  alias: Bedroom Light On
  triggers:
    - trigger: time
      at: "07:30:00"
  conditions: []
  actions:
    - action: light.turn_on
      metadata: {}
      target:
        entity_id: light.shapes_0324
      data:
        effect: Morning Sky
        brightness_pct: 50
        transition: 60
- id: bedroom_light_off
  alias: Bedroom Light Off
  triggers:
    - trigger: time
      at: "08:30:00"
  conditions: []
  actions:
    - action: light.turn_off
      metadata: {}
      target:
        entity_id: light.shapes_0324
      data:
        transition: 60
