services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.17.2
    cap_drop: [ ALL, ]
    cap_add: [ CHOWN, FOWNER, SETGID, SETUID, ]
    depends_on:
      traefik:
        condition: service_healthy
    devices:
      - /dev/apex_0:/dev/apex_0
    env_file:
      - ${REPOS_DIR:-/opt/repos}/Configurations/frigate.env
    labels:
      dd.tag.family: loose
      dd.tag.include: ^v\d+\.\d+\.\d+$$
      dd.watch: "true"
      traefik.docker.network: traefik-network
      traefik.http.routers.frigate-router.entrypoints: lan
      traefik.http.routers.frigate-router.rule: Host(`frigate.bob.house`)
      traefik.http.routers.frigate-router.tls: "true"
      traefik.http.services.frigate-service.loadbalancer.server.port: "5000"
    networks:
      default: null
      traefik: null
    profiles: [ security, ]
    security_opt: [ no-new-privileges=true, ]
    shm_size: 192mb
    volumes:
      - ./configs/frigate.yaml:/config/config.yaml:rw
      - ${DATA_DIR:-/opt/appdata}/frigate/:/config/:rw
      - /recordings/:/media/frigate/:rw
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1gb
