services:
  adguard01:
    image: adguard/adguardhome:${ADGUARDHOME_IMAGE_TAG?:missing adguardhome image tag}
    cap_drop: [ ALL, ]
    cap_add: [ DAC_OVERRIDE, NET_BIND_SERVICE, ]
    depends_on:
      traefik:
        condition: service_healthy
    labels:
      dd.tag.family: loose
      dd.tag.include: ^v\d+\.\d+\.\d+$$
      dd.watch: "true"
      dev.dozzle.group: adguard
      traefik.docker.network: traefik-network
      traefik.http.routers.adguard01-router.entrypoints: lan
      traefik.http.routers.adguard01-router.rule: Host(`adguard01.bob.house`)
      traefik.http.routers.adguard01-router.tls: "true"
      traefik.http.services.adguard01-service.loadbalancer.server.port: "3000"
    networks:
      default: null
      traefik: null
    ports:
      - 192.168.1.60:53:53/tcp
      - 192.168.1.60:53:53/udp
    profiles: [ docker1, ]
    read_only: true
    security_opt: [ no-new-privileges=true, ]
    volumes:
      - ${DATA_DIR:-/opt/appdata}/adguard01/:/opt/adguardhome/work/data/:rw
      - ./adguard01/:/opt/adguardhome/conf/:rw

  adguard20:
    image: adguard/adguardhome:${ADGUARDHOME_IMAGE_TAG?:missing adguardhome image tag}
    cap_drop: [ ALL, ]
    cap_add: [ DAC_OVERRIDE, NET_BIND_SERVICE, ]
    depends_on:
      traefik:
        condition: service_healthy
    labels:
      dd.tag.family: loose
      dd.tag.include: ^v\d+\.\d+\.\d+$$
      dd.watch: "true"
      dev.dozzle.group: adguard
      traefik.docker.network: traefik-network
      traefik.http.routers.adguard20-router.entrypoints: lan
      traefik.http.routers.adguard20-router.rule: Host(`adguard20.bob.house`)
      traefik.http.routers.adguard20-router.tls: "true"
      traefik.http.services.adguard20-service.loadbalancer.server.port: "3000"
    networks:
      default: null
      traefik: null
    ports:
      - 192.168.20.60:53:53/tcp
      - 192.168.20.60:53:53/udp
    profiles: [ docker1, ]
    read_only: true
    security_opt: [ no-new-privileges=true, ]
    volumes:
      - ${DATA_DIR:-/opt/appdata}/adguard20/:/opt/adguardhome/work/data/:rw
      - ./adguard20/:/opt/adguardhome/conf/:rw

  authentik-postgresql:
    image: docker.io/library/postgres:16-alpine
    cap_drop: [ ALL, ]
    cap_add: [ CHOWN, DAC_READ_SEARCH, FOWNER, SETGID, SETUID, ]
    env_file:
      - ${REPOS_DIR:-/opt/git}/Configurations/authentik.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    labels:
      dev.dozzle.group: authentik
      traefik.enable: "false"
    networks:
      authentik: null
    profiles: [ docker1, ]
    read_only: true
    security_opt: [ no-new-privileges=true, ]
    tmpfs: [ /var/run/postgresql/, ]
    volumes:
      - ${DATA_DIR:-/opt/appdata}/authentik/postgres/:/var/lib/postgresql/data/:rw

  authentik-server:
    image: ghcr.io/goauthentik/server:${AUTHENTIK_IMAGE_TAG?:missing authentik image tag}
    cap_drop: [ ALL, ]
    command: server
    depends_on:
      authentik-postgresql:
        condition: service_healthy
      traefik:
        condition: service_healthy
    environment:
      AUTHENTIK_ERROR_REPORTING__ENABLED: false
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
    env_file:
      - ${REPOS_DIR:-/opt/git}/Configurations/authentik.env
    labels:
      dev.dozzle.group: authentik
      traefik.docker.network: traefik-network
      traefik.http.routers.authentik-router.entrypoints: lan
      traefik.http.routers.authentik-router.rule: Host(`authentik.bob.house`)
      traefik.http.routers.authentik-router.tls: "true"
      traefik.http.services.authentik-service.loadbalancer.server.port: "9000"
    networks:
      authentik: null
      traefik: null
    profiles: [ docker1, ]
    read_only: true
    security_opt: [ no-new-privileges=true, ]
    shm_size: 512mb
    volumes:
      - ${DATA_DIR:-/opt/appdata}/authentik/data/:/data/:rw
      - ${DATA_DIR:-/opt/appdata}/authentik/custom-templates/:/templates/:rw

  authentik-worker:
    image: ghcr.io/goauthentik/server:${AUTHENTIK_IMAGE_TAG?:missing authentik image tag}
    cap_drop: [ ALL, ]
    command: worker
    depends_on:
      authentik-postgresql:
        condition: service_healthy
    environment:
      AUTHENTIK_ERROR_REPORTING__ENABLED: false
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
    env_file:
      - ${REPOS_DIR:-/opt/git}/Configurations/authentik.env
    labels:
      dev.dozzle.group: authentik
      traefik.enable: "false"
    networks:
      authentik: null
    profiles: [ docker1, ]
    read_only: true
    security_opt: [ no-new-privileges=true, ]
    shm_size: 512mb
    volumes:
      - ${DATA_DIR:-/opt/appdata}/authentik/data/:/data/:rw
      - ${DATA_DIR:-/opt/appdata}/authentik/certs/:/certs/:rw
      - ${DATA_DIR:-/opt/appdata}/authentik/custom-templates/:/templates/:rw

  baikal:
    image: ckulka/baikal:nginx
    cap_drop: [ ALL, ]
    cap_add: [ CHOWN, DAC_OVERRIDE, SETGID, SETUID, ]
    depends_on:
      traefik:
        condition: service_healthy
    labels:
      traefik.http.routers.baikal-router.entrypoints: lan
      traefik.http.routers.baikal-router.rule: Host(`baikal.bob.house`)
      traefik.http.routers.baikal-router.tls: "true"
      traefik.http.services.baikal-service.loadbalancer.server.port: "80"
    networks:
      traefik: null
    profiles: [ docker1, ]
    security_opt: [ no-new-privileges=true, ]
    volumes:
      - ${DATA_DIR:-/opt/appdata}/baikal/config/:/var/www/baikal/config/:rw
      - ${DATA_DIR:-/opt/appdata}/baikal/data/:/var/www/baikal/Specific/:rw

  dagu:
    image: ghcr.io/dagucloud/dagu:${DAGU_IMAGE_TAG?:missing dagu image tag}
    cap_drop: [ ALL, ]
    command: ["dagu", "start-all"]
    entrypoint: []
    environment:
      DAGU_HOME: /var/lib/dagu
      DAGU_DAGS_DIR: /opt/dagu/dags
      DAGU_TZ: Etc/UTC
    depends_on:
      traefik:
        condition: service_healthy
    labels:
      dd.tag.family: loose
      dd.tag.include: ^\d+\.\d+\.\d+$$
      dd.watch: "true"
      traefik.docker.network: traefik-network
      traefik.http.routers.dagu-router.entrypoints: lan
      traefik.http.routers.dagu-router.rule: Host(`dagu.bob.house`)
      traefik.http.routers.dagu-router.tls: "true"
      traefik.http.services.dagu-service.loadbalancer.server.port: "8080"
    networks:
      default: null
      traefik: null
    profiles: [ docker1, ]
    secrets:
      - source: id_rsa
      - source: known_hosts
    security_opt: [ no-new-privileges=true, ]
    tmpfs:
      [
        /var/lib/dagu/logs/,
        /var/lib/dagu/data/dag-runs/,
        /opt/dagu/dags/docs/,
        /opt/dagu/dags/memory/,
      ]
    user: "0:0"
    volumes:
      - ${DATA_DIR:-/opt/appdata}/dagu/:/var/lib/dagu/:rw
      - ./dagu/:/opt/dagu/dags/:rw
      - ${REPOS_DIR:-/opt/git}/Configurations/dagu.json:/var/lib/dagu/dagu.json:ro

  dozzle:
    image: amir20/dozzle:latest
    cap_drop: [ ALL, ]
    depends_on:
      socket-proxy:
        condition: service_started
      traefik:
        condition: service_healthy
    environment:
      DOZZLE_AUTH_PROVIDER: simple
      DOZZLE_NO_ANALYTICS: "true"
      DOZZLE_REMOTE_HOST: tcp://socket-proxy:2375|freeman,tcp://docker-kayshon.bob.house:2375|kayshon,tcp://docker-ransom.bob.house:2375|ransom,tcp://docker-shaxs.bob.house:2375|shaxs,tcp://docker-tana.bob.house:2375|tana
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 5s
      retries: 5
      start_period: 5s
      start_interval: 5s
    labels:
      traefik.docker.network: traefik-network
      traefik.http.routers.dozzle-router.entrypoints: lan
      traefik.http.routers.dozzle-router.rule: Host(`dozzle.bob.house`)
      traefik.http.routers.dozzle-router.tls: "true"
      traefik.http.services.dozzle-service.loadbalancer.server.port: "8080"
    networks:
      default: null
      socket-proxy: null
      traefik: null
    profiles: [ docker1, ]
    read_only: true
    security_opt: [ no-new-privileges=true, ]
    volumes:
      - ./dozzle/:/data/:ro

  forgejo:
    image: codeberg.org/forgejo/forgejo:15
    cap_drop: [ ALL, ]
    cap_add: [ CHOWN, DAC_OVERRIDE, FOWNER, SETGID, SETUID, SYS_CHROOT, ]
    depends_on:
      forgejo-db:
        condition: service_healthy
      traefik:
        condition: service_healthy
    env_file:
      - ${REPOS_DIR:-/opt/git}/Configurations/forgejo.env
    environment:
      FORGEJO__database__DB_TYPE: postgres
      FORGEJO__database__HOST: forgejo-db:5432
      FORGEJO__database__NAME: forgejo
      USER_UID: "1000"
      USER_GID: "1000"
    labels:
      dev.dozzle.group: forgejo
      traefik.docker.network: traefik-network
      traefik.http.routers.forgejo-router.entrypoints: lan
      traefik.http.routers.forgejo-router.rule: Host(`git.bob.house`)
      traefik.http.routers.forgejo-router.tls: "true"
      traefik.http.routers.forgejo-router.service: forgejo-service
      traefik.http.services.forgejo-service.loadbalancer.server.port: "3000"
      traefik.tcp.routers.forgejo-ssh-router.entrypoints: ssh
      traefik.tcp.routers.forgejo-ssh-router.rule: HostSNI(`*`)
      traefik.tcp.routers.forgejo-ssh-router.service: forgejo-ssh-service
      traefik.tcp.services.forgejo-ssh-service.loadbalancer.server.port: "22"
    networks:
      forgejo: null
      traefik: null
    profiles: [ docker1, ]
    security_opt: [ no-new-privileges=true, ]
    volumes:
      - ${DATA_DIR:-/opt/appdata}/forgejo/data/:/data/:rw
      - /etc/localtime:/etc/localtime:ro

  forgejo-db:
    image: postgres:14
    cap_drop: [ ALL, ]
    cap_add: [ CHOWN, DAC_READ_SEARCH, FOWNER, SETGID, SETUID, ]
    env_file:
      - ${REPOS_DIR:-/opt/git}/Configurations/forgejo.env
    environment:
      POSTGRES_DB: forgejo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    labels:
      dev.dozzle.group: forgejo
      traefik.enable: "false"
    networks:
      forgejo: null
    profiles: [ docker1, ]
    security_opt: [ no-new-privileges=true, ]
    volumes:
      - ${DATA_DIR:-/opt/appdata}/forgejo/db/:/var/lib/postgresql/data/:rw

  gatus:
    image: ghcr.io/twin/gatus:stable
    cap_drop: [ ALL, ]
    cap_add: [ NET_RAW, ]
    depends_on:
      traefik:
        condition: service_healthy
    env_file:
      - ${REPOS_DIR:-/opt/git}/Configurations/gatus.env
    environment:
      GATUS_CONFIG_PATH: /config
      NTFY_TOPIC: 364d0bdedc5b0bc275b048dc42e342460fb535dc1efcc5daf35460bf4ba4c26e
    labels:
      traefik.docker.network: traefik-network
      traefik.http.routers.gatus-router.entrypoints: lan
      traefik.http.routers.gatus-router.rule: Host(`gatus.bob.house`)
      traefik.http.routers.gatus-router.tls: "true"
      traefik.http.services.gatus-service.loadbalancer.server.port: "8080"
    networks:
      default: null
      socket-proxy: null
      traefik: null
    profiles: [ docker1, ]
    read_only: true
    security_opt: [ no-new-privileges=true, ]
    volumes:
      - ./gatus/:/config/:ro
      - ${DATA_DIR:-/opt/appdata}/gatus/sqlite-db/:/data/:rw

  glance:
    image: glanceapp/glance:latest
    cap_drop: [ ALL, ]
    depends_on:
      traefik:
        condition: service_healthy
    labels:
      traefik.docker.network: traefik-network
      traefik.http.routers.glance-router.entrypoints: lan
      traefik.http.routers.glance-router.rule: Host(`glance.bob.house`)
      traefik.http.routers.glance-router.tls: "true"
      traefik.http.services.glance-service.loadbalancer.server.port: "8080"
    networks:
      default: null
      traefik: null
    profiles: [ docker1, ]
    read_only: true
    security_opt: [ no-new-privileges=true, ]
    tmpfs: [ /app/assets/, ]
    volumes:
      - ./glance.yml:/app/config/glance.yml:ro
      - /etc/localtime:/etc/localtime:ro

  go2rtc:
    image: alexxit/go2rtc:latest
    cap_drop: [ ALL, ]
    environment:
      TZ: Etc/UTC
    env_file:
      - ${REPOS_DIR:-/opt/git}/Configurations/go2rtc.env
    labels:
      traefik.http.routers.go2rtc-router.entrypoints: lan
      traefik.http.routers.go2rtc-router.rule: Host(`go2rtc.bob.house`)
      traefik.http.routers.go2rtc-router.tls: "true"
      traefik.http.services.go2rtc-service.loadbalancer.server.port: "1984"
    profiles: [ docker1, ]
    read_only: true
    security_opt: [ no-new-privileges=true, ]
    volumes:
      - ./go2rtc/:/config/:ro

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    cap_drop: [ ALL, ]
    cap_add: [ CHOWN, DAC_OVERRIDE, NET_ADMIN, SETGID, SETUID, ]
    depends_on:
      socket-proxy:
        condition: service_started
      traefik:
        condition: service_healthy
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.bob.house
      HOSTNAME: 0.0.0.0
      PUID: "1000"
      PGID: "1000"
    env_file:
      - ${REPOS_DIR:-/opt/git}/Configurations/homepage.env
    extra_hosts:
      - host.docker.internal=host-gateway
    labels:
      traefik.docker.network: traefik-network
      traefik.http.routers.homepage-router.entrypoints: lan
      traefik.http.routers.homepage-router.rule: Host(`homepage.bob.house`)
      traefik.http.routers.homepage-router.tls: "true"
      traefik.http.services.homepage-service.loadbalancer.server.port: "3000"
    networks:
      default: null
      socket-proxy: null
      traefik: null
    profiles: [ docker1, ]
    security_opt: [ no-new-privileges=true, ]
    tmpfs: [ /app/config/logs/, ]
    volumes:
      - ./homepage/config/:/app/config/:rw
      - ./homepage/icons/:/app/public/icons/:ro
      - ./homepage/images/:/app/public/images/:ro

  portainer:
    image: portainer/portainer-ce:latest
    cap_drop: [ ALL, ]
    command: -H tcp://socket-proxy:2375
    depends_on:
      socket-proxy:
        condition: service_started
      traefik:
        condition: service_healthy
    labels:
      traefik.docker.network: traefik-network
      traefik.http.routers.portainer-router.entrypoints: lan
      traefik.http.routers.portainer-router.rule: Host(`portainer.bob.house`)
      traefik.http.routers.portainer-router.tls: "true"
      traefik.http.services.portainer-service.loadbalancer.server.port: "9000"
    networks:
      default: null
      socket-proxy: null
      traefik: null
    profiles: [ docker1, ]
    read_only: true
    security_opt: [ no-new-privileges=true, ]
    tmpfs: [ /data/backups/, ]
    volumes:
      - ${DATA_DIR:-/opt/appdata}/portainer/:/data/:rw

  prometheus:
    image: prom/prometheus:latest
    cap_drop: [ ALL, ]
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      traefik:
        condition: service_healthy
    extra_hosts:
      - host.docker.internal=host-gateway
    labels:
      traefik.docker.network: traefik-network
      traefik.http.routers.prometheus-router.entrypoints: lan
      traefik.http.routers.prometheus-router.rule: Host(`prometheus.bob.house`)
      traefik.http.routers.prometheus-router.tls: "true"
      traefik.http.services.prometheus-service.loadbalancer.server.port: "9090"
    networks:
      default: null
      traefik: null
    profiles: [ docker1, ]
    read_only: true
    security_opt: [ no-new-privileges=true, ]
    user: root
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ${DATA_DIR:-/opt/appdata}/prometheus/:/prometheus/:rw

  squid:
    image: ubuntu/squid:latest
    cap_drop: [ ALL, ]
    cap_add: [ DAC_OVERRIDE, SETGID, SETUID, ]
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      TZ: Etc/UTC
    labels:
      traefik.enable: "false"
    network_mode: service:gluetun
    profiles: [ docker1, ]
    read_only: true
    security_opt: [ no-new-privileges=true, ]
    tmpfs: [ /run/, ]
    volumes:
      - ./squid.conf:/etc/squid/squid.conf:ro
      - ${DATA_DIR:-/opt/appdata}/squid/:/var/spool/squid/:rw
      - squid-log:/var/log/squid/:rw

  sshwifty:
    image: niruix/sshwifty:latest
    cap_drop: [ ALL, ]
    depends_on:
      traefik:
        condition: service_healthy
    labels:
      traefik.docker.network: traefik-network
      traefik.http.routers.sshwifty-router.entrypoints: lan
      traefik.http.routers.sshwifty-router.rule: Host(`sshwifty.bob.house`)
      traefik.http.routers.sshwifty-router.tls: "true"
      traefik.http.services.sshwifty-service.loadbalancer.server.port: "8182"
    networks:
      default: null
      traefik: null
    profiles: [ docker1, ]
    read_only: true
    secrets:
      - source: id_rsa
    security_opt: [ no-new-privileges=true, ]
    user: root
    volumes:
      - ./sshwifty.conf.json:/root/.config/sshwifty.conf.json:ro
