services:
  identityserver:
    image: eassbhhtgu/identity-server:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      HTTP_PORTS: "80"
      Kestrel:Certificates:Default:KeyPath: /etc/certs/localhost.key
      Kestrel:Certificates:Default:Path: /etc/certs/localhost.crt

      ApiScopes:0:Name: scope1
      Clients:0:AllowedGrantTypes:0: client_credentials
      Clients:0:AllowedScopes:0: scope1
      Clients:0:ClientId: client1
      Clients:0:ClientSecrets:0:Value: WxFhjC5EAnh30M0JIe0Wa58Xb1BYf8kedTTdKUbbd9Y=
    labels:
      traefik.http.routers.identityserver-router.rule: Host(`identityserver`)
      traefik.http.routers.identityserver-router.tls: "true"
      traefik.http.services.identityserver-service.loadbalancer.server.port: "80"
    secrets:
      - source: localhost_crt
        target: /etc/certs/localhost.crt
      - source: localhost_key
        target: /etc/certs/localhost.key

  nuget:
    image: bagetter/bagetter:latest
    environment:
      ApiKey: ${NuGetServerApiKey:-8e7b324ee43b689f77c2f95b099fd6f5}
    labels:
      traefik.http.routers.nuget-router.rule: Host(`baget`) || Host(`nuget`)
      traefik.http.routers.nuget-router.tls: "true"
      traefik.http.services.nuget-service.loadbalancer.server.port: "8080"
    volumes:
      - ${USERPROFILE}\bagetter-data:/data:rw

  pihole:
    image: pihole/pihole:latest
    dns:
      - 127.0.0.1
      - 9.9.9.9
      - 9.9.9.10
    environment:
      DNS1: 9.9.9.9
      DNS2: 9.9.9.10
      TZ: UTC
      WEBPASSWORD: ${PIHOLE_WEB_PASSWORD:-76c9eca2bced3e751a47c188afe6fd9d}
    labels:
      traefik.http.routers.pihole-router.rule: Host(`pihole`)
      traefik.http.routers.pihole-router.tls: "true"
      traefik.http.services.pihole-service.loadbalancer.server.port: "80"
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
    volumes:
      - ${USERPROFILE}\pihole-data\data\:/etc/pihole/:rw
      - ${USERPROFILE}\pihole-data\dnsmasq\:/etc/dnsmasq.d/:rw

  traefik:
    image: traefik:latest
    command:
      - --api.insecure=true
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --providers.file.directory=/etc/traefik/dynamic_conf/
    labels:
      traefik.http.routers.traefik-router.rule: Host(`traefik`)
      traefik.http.routers.traefik-router.tls: "true"
      traefik.http.services.traefik-service.loadbalancer.server.port: "8080"
    ports:
      - 443:443/tcp
    secrets:
      - source: localhost_crt
        target: /etc/certs/localhost.crt
      - source: localhost_key
        target: /etc/certs/localhost.key
    volumes:
      - ./traefik.yml:/etc/traefik/dynamic_conf/conf.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock

secrets:
  localhost_crt:
    file: ${USERPROFILE}\.aspnet\https\localhost.crt
  localhost_key:
    file: ${USERPROFILE}\.aspnet\https\localhost.key
