function Add-Program([string] $Id) {
	winget install --accept-package-agreements --accept-source-agreements --exact --id "$Id"
}

#Add-Program '3Dconnexion.3DxWare.10'
Add-Program '7zip.7zip'
Add-Program 'Brother.iPrintScan'
Add-Program 'CodecGuide.K-LiteCodecPack.Standard'
Add-Program 'Discord.Discord'
Add-Program 'Docker.DockerDesktop'
Add-Program 'DominikReichl.KeePass'
#Add-Program 'ElectronicArts.EADesktop'
Add-Program 'Exercism.CLI'
Add-Program 'Fork.Fork'
Add-Program 'Gyan.FFmpeg'
Add-Program 'IDRIX.VeraCrypt'
Add-Program 'jqlang.jq'
Add-Program 'LibreWolf.LibreWolf'
#Add-Program 'MusicBrainz.Picard'
Add-Program 'Mythicsoft.AgentRansack'
Add-Program 'Notepad++.Notepad++'
Add-Program 'OBSProject.OBSStudio'
#Add-Program 'OpenRGB.OpenRGB'
#Add-Program 'Oracle.MySQLWorkbench'
#Add-Program 'Piriform.CCleaner'
Add-Program 'Piriform.Defraggler'
Add-Program 'Proton.ProtonVPN'
Add-Program 'RaspberryPiFoundation.RaspberryPiImager'
Add-Program 'rocksdanister.LivelyWallpaper'
Add-Program 'Rufus.Rufus'
Add-Program 'ShareX.ShareX'
Add-Program 'Valve.Steam'
Add-Program 'WinDirStat.WinDirStat'
#Add-Program 'Xencelabs.Driver'

#Add-Program 'Elgato.CameraHub'
Add-Program 'Elgato.StreamDeck'
#Add-Program 'Elgato.WaveLink'

Add-Program 'Microsoft.Git'
Add-Program 'Microsoft.PowerShell'
Add-Program 'Microsoft.Sysinternals.RDCMan'
Add-Program 'Microsoft.Teams'
Add-Program 'Microsoft.VisualStudio.Community'
Add-Program 'Microsoft.VisualStudioCode'
Add-Program 'Microsoft.WindowsTerminal'
