services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Etc/UTC
      WEBUI_PORT: "8080"
      TORRENTING_PORT: "6881"
    ports:
      - 6881:6881/tcp
      - 6881:6881/udp
      - 8080:8080/tcp
    volumes:
      - ${USERPROFILE}\qbittorrent-data\:/config/:rw
      - E:\Downloads\:/downloads/:rw

  sickgear:
    image: sickgear/sickgear:latest
    ports:
      - 8081:8081/tcp
    volumes:
      - ${USERPROFILE}\sickgear-data\:/data/:rw
      - D:\anime\:/media/anime/:rw
      - D:\films\:/media/films/:rw
      - D:\Red-Letter Media\:/media/Red-Letter Media/:rw
      - D:\tvshows\:/media/tv/:rw
      - D:\videos\:/media/videos/:rw
      - E:\music\:/media/music/:rw
      - E:\pictures\:/media/pictures/:rw
