http:
  routers:
    pihole-router:
      entryPoints:
        - "websecure"
      rule: "Host(`pihole`)"
      service: "pihole-service"
      tls: "true"
    router1-router:
      entryPoints:
        - "websecure"
      rule: "Host(`router1`)"
      service: "router1-service"
      tls: "true"
  services:
    pihole-service:
      loadBalancer:
        servers:
        - url: "http://192.168.1.80"
    router1-service:
      loadBalancer:
        servers:
        - url: "http://192.168.1.10"

tls:
  certificates:
    - certFile: /etc/certs/localhost.crt
      keyFile: /etc/certs/localhost.key
