http:
  routers:
    jellyfin-router:
      entryPoints:
        - "websecure"
      rule: "Host(`jellyfin`)"
      service: "jellyfin-service"
      tls: "true"
  services:
    jellyfin-service:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:8096/"

tls:
  certificates:
    - certFile: /etc/certs/localhost.crt
      keyFile: /etc/certs/localhost.key
