---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings

background: /images/control.png

cardBlur: sm # sm, "", md, etc... see https://tailwindcss.com/docs/backdrop-blur

color: zinc # amber, blue, cyan, emerald, fuchsia, gray, green, indigo, lime, neutral, pink, purple, red, rose, sky, slate, stone, teal, violet, white, yellow, zinc

disableCollapse: true

headerStyle: boxed

layout:
  Essentials:
    columns: 4
    style: row
    tab: Main
  Developer:
    tab: Main
  Social:
    tab: Main
  Entertainment:
    tab: Main
  Services:
    columns: 4
    style: row
    tab: Monitoring
  Glances:
    columns: 4
    style: row
    tab: Monitoring
  Portainer:
    columns: 4
    style: row
    tab: Monitoring
  Traefik:
    columns: 4
    style: row
    tab: Monitoring
  Uptime Kuma:
    columns: 4
    style: row
    tab: Monitoring
  Media:
    columns: 4
    style: row
    tab: Media
  All:
    columns: 4
    style: row
    tab: All

providers:
  finnhub: {{HOMEPAGE_VAR_PROVIDERS_FINNHUB}}
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

statusStyle: "dot"
