global:
  scrape_interval: 5s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'machine'
    static_configs:
      - targets: ['192.168.1.50:9273']
      - targets: ['host.docker.internal:9273']
      - targets: ['billups.bob.house:9273']
      - targets: ['ransom.bob.house:9273']
      - targets: ['shaxs.bob.house:9273']
      - targets: ['tana.bob.house:9273']

  - job_name: 'traefik'
    scheme: https
    static_configs:
      - targets: ['traefik-billups.bob.house']
      - targets: ['traefik.bob.house']
      - targets: ['traefik-ransom.bob.house']
      - targets: ['traefik-shaxs.bob.house']
      - targets: ['traefik-tana.bob.house']
