http:
  routers:
    homeassistant-router:
      entryPoints:
        - "websecure"
      rule: "Host(`homeassistant.bob.house`)"
      service: "homeassistant-service"
      tls: "true"
    iot-switch-router:
      entryPoints:
        - "websecure"
      rule: "Host(`iot-switch.bob.house`)"
      service: "iot-switch-service"
      tls: "true"
    kopia-kayshon-router:
      entryPoints:
        - "websecure"
      rule: "Host(`kopia-kayshon.bob.house`)"
      service: "kopia-kayshon-service"
      tls: "true"
    leafwiki-router:
      entryPoints:
        - "websecure"
      rule: "Host(`leafwiki.bob.house`)"
      service: "leafwiki-service"
      tls: "true"
    main-router-router:
      entryPoints:
        - "websecure"
      rule: "Host(`main-router.bob.house`)"
      service: "main-router-service"
      tls: "true"
    main-switch-router:
      entryPoints:
        - "websecure"
      rule: "Host(`main-switch.bob.house`)"
      service: "main-switch-service"
      tls: "true"
    miasma-router:
      entryPoints:
        - "websecure"
      rule: "Host(`miasma.bob.house`)"
      service: "miasma-service"
      tls: "true"
    traefik-kayshon-router:
      entryPoints:
        - "websecure"
      rule: "Host(`traefik-kayshon.bob.house`)"
      service: "traefik-kayshon-service"
      tls: "true"
  services:
    homeassistant-service:
      loadBalancer:
        servers:
        - url: "http://192.168.20.80:8123"
    iot-switch-service:
      loadBalancer:
        servers:
        - url: "http://192.168.20.5"
    kopia-kayshon-service:
      loadBalancer:
        servers:
        - url: "http://192.168.20.85:51515"
    leafwiki-service:
      loadBalancer:
        servers:
        - url: "http://192.168.20.85:4040"
    main-router-service:
      loadBalancer:
        servers:
        - url: "http://192.168.1.1"
    main-switch-service:
      loadBalancer:
        servers:
        - url: "http://192.168.1.5"
    miasma-service:
      loadBalancer:
        servers:
        - url: "http://192.168.20.85:9999"
    traefik-kayshon-service:
      loadBalancer:
        servers:
        - url: "http://192.168.20.85:8080"
