http:
  middlewares:
    method-whitelist-plugin:
      plugin:
        method-whitelist:
          Message: "Method Not Allowed"
          Methods:
            - GET
  routers:
    leafwiki-router:
      entryPoints:
        - "websecure"
      middlewares:
        - method-whitelist-plugin
      rule: "Host(`www.bob.house`)"
      service: "leafwiki-service"
      tls: "true"
    miasma-router:
      entryPoints:
        - "websecure"
      rule: "Host(`miasma.bob.house`)"
      service: "miasma-service"
      tls: "true"
  services:
    leafwiki-service:
      loadBalancer:
        servers:
        - url: "http://192.168.20.85:4040"
    miasma-service:
      loadBalancer:
        servers:
        - url: "http://192.168.20.85:9999"
