services:
  authentik-postgresql:
    image: docker.io/library/postgres:alpine
    environment:
      POSTGRES_DB: ${AUTHENTIK_POSTGRES_DB:-authentik}
      POSTGRES_PASSWORD: ${AUTHENTIK_POSTGRES_PASSWORD:?database password required}
      POSTGRES_USER: ${AUTHENTIK_POSTGRES_USER:-authentik}
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    networks:
      authentik: null
    volumes:
      - ~/.authentik/postgres/:/var/lib/postgresql/data/:rw

  authentik-redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    networks:
      authentik: null
    volumes:
      - ~/.authentik/redis/:/data/:rw

  authentik-server:
    image: ghcr.io/goauthentik/server:latest
    command: server
    depends_on:
      authentik-postgresql:
        condition: service_healthy
      authentik-redis:
        condition: service_healthy
    environment:
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__NAME: ${AUTHENTIK_POSTGRES_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_POSTGRES_PASSWORD:?postgres database password required}
      AUTHENTIK_POSTGRESQL__USER: ${AUTHENTIK_POSTGRES_USER:-authentik}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?authentik secret key required}
    env_file:
      - .env
    labels:
      traefik.http.routers.authentik-router.entrypoints: websecure
      traefik.http.routers.authentik-router.rule: Host(`authentik.bob.house`)
      traefik.http.routers.authentik-router.tls: "true"
      traefik.http.services.authentik-service.loadbalancer.server.port: "9000"
    networks:
      authentik: null
      _proxy:
        ipv4_address: 172.18.0.3
    volumes:
      - ~/.authentik/media/:/media/:rw
      - ~/.authentik/custom-templates/:/templates/:rw

  authentik-worker:
    image: ghcr.io/goauthentik/server:latest
    command: worker
    depends_on:
      authentik-postgresql:
        condition: service_healthy
      authentik-redis:
        condition: service_healthy
    environment:
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__NAME: ${AUTHENTIK_POSTGRES_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_POSTGRES_PASSWORD:?postgres database password required}
      AUTHENTIK_POSTGRESQL__USER: ${AUTHENTIK_POSTGRES_USER:-authentik}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?authentik secret key required}
    env_file:
      - .env
    # `user: root` and the docker socket volume are optional.
    # See more for the docker socket integration here:
    # https://goauthentik.io/docs/outposts/integrations/docker
    # Removing `user: root` also prevents the worker from fixing the permissions
    # on the mounted folders, so when removing this make sure the folders have the correct UID/GID
    # (1000:1000 by default)
    networks:
      authentik: null
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ~/.authentik/media/:/media/:rw
      - ~/.authentik/certs/:/certs/:rw
      - ~/.authentik/custom-templates/:/templates/:rw

  dozzle:
    image: amir20/dozzle:latest
    environment:
      DOZZLE_REMOTE_AGENT: ahti:7007,marshall:7007,pope:7007
    labels:
      traefik.http.routers.dozzle-router.entrypoints: websecure
      traefik.http.routers.dozzle-router.rule: Host(`dozzle.bob.house`)
      traefik.http.routers.dozzle-router.tls: "true"
      traefik.http.services.dozzle-service.loadbalancer.server.port: "8080"
    networks:
      _proxy:
        ipv4_address: 172.18.0.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  glances:
    image: nicolargo/glances:latest
    environment:
      GLANCES_OPT: -w
    labels:
      traefik.http.routers.glances-router.entrypoints: websecure
      traefik.http.routers.glances-router.rule: Host(`glances-trench.bob.house`)
      traefik.http.routers.glances-router.tls: "true"
      traefik.http.services.glances-service.loadbalancer.server.port: "61208"
    networks:
      _proxy:
        ipv4_address: 172.18.0.5
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    labels:
      traefik.http.routers.homeassistant-router.entrypoints: websecure
      traefik.http.routers.homeassistant-router.rule: Host(`homeassistant.bob.house`)
      traefik.http.routers.homeassistant-router.tls: "true"
      traefik.http.services.homeassistant-service.loadbalancer.server.port: "8123"
    networks:
      _proxy:
        ipv4_address: 172.18.0.6
    volumes:
      - ~/.homeassistant/:/config/:rw
      - ./homeassistant/automations.yaml:/config/automations.yaml:rw
      - ./homeassistant/configuration.yaml:/config/configuration.yaml:rw
      - ./homeassistant/scenes.yaml:/config/scenes.yaml:rw
      - ./homeassistant/scripts.yaml:/config/scripts.yaml:rw
      - ./homeassistant/secrets.yaml:/config/secrets.yaml:rw

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    env_file:
      - ./.env
    labels:
      traefik.http.routers.homepage-router.entrypoints: websecure
      traefik.http.routers.homepage-router.rule: Host(`homepage.bob.house`)
      traefik.http.routers.homepage-router.tls: "true"
      traefik.http.services.homepage-service.loadbalancer.server.port: "3000"
    networks:
      _proxy:
        ipv4_address: 172.18.0.7
    volumes:
      - .\homepage\:/app/config/:rw
      - .\homepage\icons\:/app/public/icons/:ro
      - .\homepage\images\:/app/public/images/:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  portainer:
    image: portainer/portainer-ce:latest
    labels:
      traefik.http.routers.portainer-router.entrypoints: websecure
      traefik.http.routers.portainer-router.rule: Host(`portainer.bob.house`)
      traefik.http.routers.portainer-router.tls: "true"
      traefik.http.services.portainer-service.loadbalancer.server.port: "9000"
    networks:
      _proxy:
        ipv4_address: 172.18.0.8
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ~/.portainer/:/data/:rw

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    labels:
      traefik.http.routers.prometheus-router.entrypoints: websecure
      traefik.http.routers.prometheus-router.rule: Host(`prometheus.bob.house`)
      traefik.http.routers.prometheus-router.tls: "true"
      traefik.http.services.prometheus-service.loadbalancer.server.port: "9090"
    networks:
      _proxy:
        ipv4_address: 172.18.0.9
    ports:
      - 9090:9090/tcp
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ~/prometheus-data/:/prometheus/:rw

  traefik:
    image: traefik:latest
    command:
      # - --accesslog=true
      - --api.insecure=true
      - --certificatesresolvers.cloudflare.acme.dnsChallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      - --certificatesresolvers.cloudflare.acme.email=mail@bob.codes
      - --certificatesresolvers.cloudflare.acme.storage=/acme.json
      - --entrypoints.websecure.address=:443
      # TRACE  DEBUG  INFO  WARN  ERROR  FATAL  PANIC
      - --log.level=INFO
      - --metrics.prometheus=true
      - --metrics.prometheus.addentrypointslabels=true
      - --metrics.prometheus.addrouterslabels=true
      - --metrics.prometheus.addserviceslabels=true
      - --providers.docker
      - --providers.file.directory=/etc/traefik/dynamic_conf/
    environment:
      CF_API_EMAIL: mail@bob.codes
      CF_DNS_API_TOKEN_FILE: /CF_DNS_API_TOKEN
    labels:
      traefik.http.routers.traefik-router.entrypoints: websecure
      traefik.http.routers.traefik-router.rule: Host(`traefik.bob.house`)
      traefik.http.routers.traefik-router.tls: "true"
      traefik.http.routers.traefik-router.tls.certresolver: cloudflare
      traefik.http.routers.traefik-router.tls.domains[0].main: bob.house
      traefik.http.routers.traefik-router.tls.domains[0].sans: '*.bob.house'
      traefik.http.services.traefik-service.loadbalancer.server.port: "8080"
    networks:
      _proxy:
        ipv4_address: 172.18.0.2
    ports:
      - 443:443/tcp
    volumes:
      - ~/.certs/acme.json:/acme.json:rw
      - ~/.certs/CF_DNS_API_TOKEN:/CF_DNS_API_TOKEN:ro
      - ./traefik.yml:/etc/traefik/dynamic_conf/conf.yml:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  uptimekuma:
    image: louislam/uptime-kuma:latest
    labels:
      traefik.http.routers.uptimekuma-router.entrypoints: websecure
      traefik.http.routers.uptimekuma-router.rule: Host(`uptimekuma.bob.house`)
      traefik.http.routers.uptimekuma-router.tls: "true"
      traefik.http.services.uptimekuma-service.loadbalancer.server.port: "3001"
    networks:
      _proxy:
        ipv4_address: 172.18.0.10
    volumes:
      - ~/.uptimekuma/:/app/data/:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  _proxy:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/26
  authentik:
    driver: bridge
    internal: "true"
