services:
  dozzle:
    image: amir20/dozzle:latest
    command: agent
    ports:
      - 7007:7007/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    devices:
      - /dev/apex_0:/dev/apex_0
    environment:
      FRIGATE_RTSP_PASSWORD: ${FRIGATE_RTSP_PASSWORD:-d2553245df3caca802ffe5dfb8d85a22}
    ports:
      - 5000:5000/tcp
    shm_size: "128mb"
    volumes:
      - ~/.frigate/config/:/config/:rw
      - ~/.frigate/media/:/media/frigate/:rw
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000

  glances:
    image: nicolargo/glances:latest
    environment:
      GLANCES_OPT: -w
    pid: host
    ports:
      - 61208:61208/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro

  portainer:
    image: portainer/agent:latest
    ports:
      - 9001:9001/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /var/lib/docker/volumes/:/var/lib/docker/volumes/:rw
      - /:/host/:rw

  wireshark:
    image: lscr.io/linuxserver/wireshark:latest
    cap_add:
      - NET_ADMIN
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Etc/UTC
    network_mode: host
    security_opt:
      - seccomp:unconfined #optional
    volumes:
      - ~/.wireshark/:/config/:rw
