services:
  dozzle:
    image: amir20/dozzle:latest
    command: agent
    environment:
      DOZZLE_HOSTNAME: marshall
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 5s
      retries: 5
      start_period: 5s
      start_interval: 5s
    ports:
      - 7007:7007/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    devices:
      - /dev/apex_0:/dev/apex_0
    env_file:
      - ~/Configurations/frigate.env
    ports:
      - 5000:5000/tcp
    shm_size: "128mb"
    volumes:
      - ./frigate.yaml:/config/config.yaml:rw
      - ~/.frigate/config/:/config/:rw
      - /srv/frigate/media/:/media/frigate/:rw
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000

  glances:
    image: nicolargo/glances:latest
    environment:
      GLANCES_OPT: -w
    pid: host
    ports:
      - 61208:61208/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro

  portainer:
    image: portainer/agent:latest
    ports:
      - 9001:9001/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /var/lib/docker/volumes/:/var/lib/docker/volumes/:rw
      - /:/host/:rw
