---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- Media Server:
    - Glances:
        href: https://glances3/
        icon: glances.png
        ping: ahti
        siteMonitor: http://ahti:61208
        widget:
          type: glances
          url: http://ahti:61208
          version: 4
          metric: network:eth0
          refreshInterval: 5000
          pointsLimit: 15
    - Jellyfin:
        href: https://jellyfin/web/
        icon: jellyfin.svg
        ping: ahti
        siteMonitor: https://jellyfin/health
        widget:
          type: jellyfin
          url: https://jellyfin
          key: 8c70503628304809803c593fa339b921
          enableBlocks: true # optional, defaults to false
          enableNowPlaying: true # optional, defaults to true
          enableUser: true # optional, defaults to false
          # showEpisodeNumber: true # optional, defaults to false
          expandOneStreamToTwoRows: false # optional, defaults to true
    - MeTube:
        href: https://metube/
        icon: metube.svg
        ping: ahti
        siteMonitor: https://metube
    - qBittorrent:
        href: https://qbittorrent
        icon: qbittorrent.svg
        ping: ahti
        siteMonitor: https://qbittorrent
        widget:
          type: qbittorrent
          url: https://qbittorrent
          username: admin
          password: password
    - Sick Gear:
        href: https://sickgear/
        icon: sickbeard.svg
        ping: ahti
        siteMonitor: https://sickgear

- Server 1:
    - Change Detection:
        href: https://changedetection/
        icon: changedetection-io.png
        ping: changedetection
        siteMonitor: http://changedetection:5000
        widget:
          type: changedetectionio
          url: http://changedetection:5000
          key: b907fb20b376747d27db01e8e4056ce7
    - Docker Registry:
        href: https://registry/
        icon: docker-moby.svg
        ping: registry
        siteMonitor: http://registry:5000/v2/_catalog
    - Glances:
        href: https://glances1/
        icon: glances.png
        ping: glances1
        siteMonitor: http://glances1:61208
        widget:
          type: glances
          url: http://glances1:61208
          version: 4
          metric: network:eth0
          refreshInterval: 5000
          pointsLimit: 15
    - Home Assistant:
        href: https://homeassistant/
        icon: home-assistant.svg
        ping: homeassistant
        siteMonitor: http://homeassistant:8123
        widget:
          type: homeassistant
          url: http://homeassistant:8123
          key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI3ZDZiOTUyYzYyOWU0ZDliYjFhMDVhMDMwYTAxOTdkNCIsImlhdCI6MTcyODkxODM0NywiZXhwIjoyMDQ0Mjc4MzQ3fQ.1jiQ_KHIzSI60IXJSJPYv6MOGahpinzaempeW__lLi4
          custom:
            - label: spotlight
              state: light.keylight
            - label: nanoleaf
              state: light.shapes_0324
            - label: bedroom
              state: light.bedroom_main
            - label: pc
              state: sensor.pc_current_consumption
    - httpbin:
        href: https://httpbin/
        icon: /icons/httpbin.png
        ping: httpbin
        siteMonitor: http://httpbin:8080
    - moodist:
        href: https://moodist/?share=%7B%22rain-on-window%22%3A0.07%2C%22crowd%22%3A0.59%2C%22inside-a-train%22%3A0.36%2C%22brown-noise%22%3A0.12%7D
        icon: /icons/moodist.svg
        ping: moodist
        siteMonitor: http://moodist:8080
    - ntfy:
        href: https://ntfy/
        icon: ntfy-light.png
        ping: ntfy
        siteMonitor: http://ntfy
    - NuGet:
        href: https://nuget/
        icon: microsoft.svg
        ping: nuget
        siteMonitor: http://nuget:8080/v3/index.json
    - Planka:
        href: https://planka/
        icon: planka.svg
        ping: planka
        siteMonitor: http://planka:1337
    - Speedtest:
        href: https://speedtest/
        icon: openspeedtest.png
        ping: speedtest-tracker
        siteMonitor: http://speedtest-tracker/api/healthcheck
    - Traefik:
        href: https://traefik/dashboard/
        icon: traefik-proxy.svg
        ping: traefik
        siteMonitor: https://traefik/dashboard/
        widget:
          type: traefik
          url: https://traefik
    - Trilium:
        href: https://trilium/
        icon: trilium.svg
        ping: trilium
        siteMonitor: http://trilium:8080/login
    - Uptime Kuma:
        href: https://uptimekuma/dashboard/
        icon: uptime-kuma.svg
        ping: uptimekuma
        siteMonitor: http://uptimekuma:3001/dashboard/
        widget:
          type: uptimekuma
          url: http:///uptimekuma:3001
          slug: statuspageslug
    - Uptime Kuma (Work):
        href: https://uptimekuma/dashboard/
        icon: uptime-kuma.svg
        ping: http://uptimekuma
        siteMonitor: http://uptimekuma:3001/dashboard/
        widget:
          type: uptimekuma
          url: http:///uptimekuma:3001
          slug: work
    - What's Up Docker:
        href: https://whatsupdocker/
        icon: whats-up-docker.svg
        ping: whatsupdocker
        siteMonitor: http://whatsupdocker:3000
        widget:
          type: whatsupdocker
          url: http://whatsupdocker:3000

- Server 2:
    - Frigate:
        href: https://frigate/
        icon: frigate.svg
        ping: marshall
        siteMonitor: https://frigate
        widget:
          type: frigate
          url: https://frigate
          enableRecentEvents: true
    - Glances:
        href: https://glances2/
        icon: glances.png
        ping: marshall
        siteMonitor: http://marshall:61208
        widget:
          type: glances
          url: http://marshall:61208
          version: 4
          metric: network:eth0
          refreshInterval: 5000
          pointsLimit: 15

- Network:
    - Main Router:
        href: https://router1/
        icon: router.svg
        ping: router1
        siteMonitor: https://router1
    - Pi-hole:
        href: https://pihole/admin
        icon: pi-hole.svg
        ping: pihole
        siteMonitor: https://pihole/admin
        widget:
          type: pihole
          url: https://pihole
          # version: 6 # required if running v6 or higher, defaults to 5
          key: 3e8964b5fabacdb7cb983a50c7d92f4fc80a52f9d9875ae6ac2dbeab5ee134b9 # optional
