---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- Media Server:
    - Jellyfin:
        href: https://jellyfin/web/
        icon: jellyfin.svg
        siteMonitor: https://jellyfin/health
        widget:
          type: jellyfin
          url: https://jellyfin
          key: 8c70503628304809803c593fa339b921
          enableBlocks: true # optional, defaults to false
          enableNowPlaying: true # optional, defaults to true
          enableUser: true # optional, defaults to false
          # showEpisodeNumber: true # optional, defaults to false
          expandOneStreamToTwoRows: false # optional, defaults to true
    - MeTube:
        href: https://metube/
        icon: metube.svg
        siteMonitor: https://metube
    - qBittorrent:
        href: https://qbittorrent
        icon: qbittorrent.svg
        siteMonitor: https://qbittorrent
        widget:
          type: qbittorrent
          url: https://qbittorrent
          username: admin
          password: password
    - Sick Gear:
        href: https://sickgear/
        icon: sickbeard.svg
        siteMonitor: https://sickgear

- Server:
    - Change Detection:
        href: https://changedetection/
        icon: changedetection-io.png
        siteMonitor: http://changedetection:5000
        widget:
          type: changedetectionio
          url: http://changedetection:5000
          key: b907fb20b376747d27db01e8e4056ce7
    - Docker Registry:
        href: https://registry/
        icon: docker-moby.svg
        siteMonitor: http://registry:5000/v2/_catalog
    - Frigate:
        href: https://frigate/
        icon: frigate.svg
        siteMonitor: https://frigate
        widget:
          type: frigate
          url: https://frigate
          enableRecentEvents: true
    - Home Assistant:
        href: https://homeassistant/
        icon: home-assistant.svg
        siteMonitor: http://homeassistant:8123
        widget:
          type: homeassistant
          url: http://homeassistant:8123
          key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI3ZDZiOTUyYzYyOWU0ZDliYjFhMDVhMDMwYTAxOTdkNCIsImlhdCI6MTcyODkxODM0NywiZXhwIjoyMDQ0Mjc4MzQ3fQ.1jiQ_KHIzSI60IXJSJPYv6MOGahpinzaempeW__lLi4
          custom:
            - label: spotlight
              state: light.keylight
            - label: nanoleaf
              state: light.shapes_0324
            - label: bedroom
              state: light.bedroom_main
            - label: pc
              state: sensor.pc_current_consumption
    - httpbin:
        href: https://httpbin/
        icon: /icons/httpbin.png
        siteMonitor: http://httpbin:8080
    - NuGet:
        href: https://nuget/
        icon: microsoft.svg
        siteMonitor: http://nuget:8080/v3/index.json
    - Planka:
        href: https://planka/
        icon: planka.svg
        siteMonitor: http://planka:1337
    - Speedtest:
        href: https://speedtest/
        icon: openspeedtest.png
        siteMonitor: http://speedtest-tracker/api/healthcheck
    - Traefik:
        href: https://traefik/dashboard/
        icon: traefik-proxy.svg
        siteMonitor: https://traefik/dashboard/
        widget:
          type: traefik
          url: https://traefik
    - Uptime Kuma:
        href: https://uptimekuma/dashboard/
        icon: uptime-kuma.svg
        siteMonitor: http://uptimekuma:3001/dashboard/
        widget:
          type: uptimekuma
          url: http:///uptimekuma:3001
          slug: statuspageslug
    - What's Up Docker:
        href: https://whatsupdocker/
        icon: whats-up-docker.svg
        siteMonitor: http://whatsupdocker:3000
        widget:
          type: whatsupdocker
          url: http://whatsupdocker:3000

- Network:
    - Main Router:
        href: https://router1/
        icon: router.svg
        siteMonitor: https://router1
    - Pi-hole:
        href: https://pihole/admin
        icon: pi-hole.svg
        siteMonitor: https://pihole/admin
        widget:
          type: pihole
          url: https://pihole
          # version: 6 # required if running v6 or higher, defaults to 5
          key: 3e8964b5fabacdb7cb983a50c7d92f4fc80a52f9d9875ae6ac2dbeab5ee134b9 # optional
