---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings

providers:
  finnhub: crs8q5pr01qvrlsu2gsgcrs8q5pr01qvrlsu2gt0
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
