services:
  dozzle:
    image: amir20/dozzle:latest
    command: agent
    ports:
      - 7007:7007/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  glances:
    image: nicolargo/glances:latest
    environment:
      GLANCES_OPT: -w
    pid: host
    ports:
      - 61208:61208/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro

  gluetun:
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      VPN_SERVICE_PROVIDER: protonvpn
      VPN_TYPE: openvpn
      OPENVPN_USER: ${OPENVPN_USER:?openvpn user required}
      OPENVPN_PASSWORD: ${OPENVPN_PASSWORD:?openvpn password required}
      SERVER_COUNTRIES: ${OPENVPN_COUNTRIES:?openvpn countries required}
      TZ: Etc/UTC
      UPDATER_PERIOD: 24h
    env_file:
      - .env
    ports:
      - 8096:8096/tcp # jellyfin
      - 5055:5055/tcp # jellyseerr
      - 8686:8686/tcp # lidarr
      - 9696:9696/tcp # prowlar
      - 6881:6881/tcp # qbittorrent
      - 6881:6881/udp
      - 8080:8082/tcp
      - 7878:7878/tcp # radarr
      - 8083:8080/tcp # sabnzbd
      - 8081:8081/tcp # sickgear
      - 8989:8989/tcp # sonarr

  jellyfin:
    image: jellyfin/jellyfin:latest
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: service:gluetun
    volumes:
      - ${USERPROFILE}\jellyfin-data\config\:/config/:rw
      - ${USERPROFILE}\jellyfin-data\cache\:/cache/:rw
      - E:\anime\:/media/anime/:rw
      - E:\films\:/media/films/:rw
      - E:\streamers\:/media/streamers/:rw
      - D:\tvshows\:/media/tv/:rw
      - E:\videos\:/media/videos/:rw
      - E:\music\:/media/music/:rw
      - E:\pictures\:/media/pictures/:rw
      - E:\youtube\:/media/tubearchivist/:rw

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      LOG_LEVEL: debug
      TZ: UTC
    network_mode: service:gluetun
    volumes:
      - ~/jellyseerr-data/:/app/config/:rw

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    network_mode: service:gluetun
    volumes:
      - ${USERPROFILE}\lidarr-data\:/config/:rw
      - E:\Downloads\sabnzbd\:/config/Downloads/complete/:rw
      - E:\Music\:/music/:rw

  metube:
    image: ghcr.io/alexta69/metube:latest
    environment:
      OUTPUT_TEMPLATE: '%(playlist_title&Playlist |)S%(playlist_title|)S%(playlist_uploader& by |)S%(playlist_uploader|)S%(playlist_autonumber& - |)S%(playlist_autonumber|)S%(playlist_count& of |)S%(playlist_count|)S%(playlist_autonumber& - |)S%(uploader,creator|UNKNOWN_AUTHOR)S %(release_date>%Y-%m-%d,upload_date>%Y-%m-%d|UNKNOWN_DATE)S - %(title|UNKNOWN_TITLE)S.%(ext)s'
      OUTPUT_TEMPLATE_PLAYLIST: '%(playlist_title&Playlist |)S%(playlist_title|)S%(playlist_uploader& by |)S%(playlist_uploader|)S%(playlist_autonumber& - |)S%(playlist_autonumber|)S%(playlist_count& of |)S%(playlist_count|)S%(playlist_autonumber& - |)S%(uploader,creator|UNKNOWN_AUTHOR)S %(release_date>%Y-%m-%d,upload_date>%Y-%m-%d|UNKNOWN_DATE)S - %(title|UNKNOWN_TITLE)S.%(ext)s'
      STATE_DIR: /data/state/
      TEMP_DIR: /data/temp/
      YTDL_OPTIONS: '{"cookiefile":"/cookies/cookies.txt","writesubtitles":true,"subtitleslangs":["en","-live_chat"],"updatetime":false,"postprocessors":[{"key":"Exec","exec_cmd":"chmod 0664","when":"after_move"},{"key":"FFmpegEmbedSubtitle","already_have_subtitle":false},{"key":"FFmpegMetadata","add_chapters":true}]}'
    ports:
      - 8082:8081/tcp
    volumes:
      - ${USERPROFILE}\metube-data\:/data/:rw
      - ~/cookies.txt:/cookies/cookies.txt:ro
      - E:\Downloads\YouTube\:/downloads/:rw

  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    environment:
      TZ: Etc\UTC
    ports:
      - 8945:8945/tcp
    volumes:
      - ~/.pinchflat/:/config/:rw
      - E:\YouTube\:/downloads/:rw

  portainer:
    image: portainer/agent:latest
    ports:
      - 9001:9001/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /var/lib/docker/volumes/:/var/lib/docker/volumes/:rw
      - C:\:/host/:rw

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Etc/UTC
    network_mode: service:gluetun
    volumes:
      - ${USERPROFILE}\prowlarr-data\:/config/:rw

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Etc/UTC
      WEBUI_PORT: "8082"
      TORRENTING_PORT: "6881"
    network_mode: service:gluetun
    volumes:
      - ${USERPROFILE}\qbittorrent-data\:/config/:rw
      - E:\Downloads\:/downloads/:rw

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    network_mode: service:gluetun
    volumes:
      - ${USERPROFILE}\radarr-data/:/config/:rw
      - E:\Downloads\sabnzbd\:/config/Downloads/complete/:rw
      - E:\Films\:/movies/:rw

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    network_mode: service:gluetun
    volumes:
      - ${USERPROFILE}\sabnzbd-data\:/config/:rw
      - E:\Downloads\sabnzbd\:/config/Downloads/complete/:rw
      - E:\Downloads\sabnzbd\incomplete\:/config/Downloads/incomplete/:rw

  sickgear:
    image: sickgear/sickgear:latest
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: service:gluetun
    volumes:
      - ${USERPROFILE}\sickgear-data\:/data/:rw
      - E:\anime\:/media/anime/:rw
      - E:\films\:/media/films/:rw
      - D:\tvshows\:/media/tv/:rw
      - E:\videos\:/media/videos/:rw
      - E:\music\:/media/music/:rw
      - E:\pictures\:/media/pictures/:rw

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    network_mode: service:gluetun
    volumes:
      - ${USERPROFILE}\sonarr-data\:/config/:rw
      - D:\tvshows\:/tv/:rw
      - E:\Downloads\sabnzbd\:/config/Downloads/complete/:rw
