services:
  glances:
    image: nicolargo/glances:latest
    environment:
      GLANCES_OPT: -w
    pid: host
    ports:
      - 61208:61208/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro

  metube:
    image: ghcr.io/alexta69/metube:latest
    environment:
      OUTPUT_TEMPLATE: '%(playlist_title&Playlist |)S%(playlist_title|)S%(playlist_uploader& by |)S%(playlist_uploader|)S%(playlist_autonumber& - |)S%(playlist_autonumber|)S%(playlist_count& of |)S%(playlist_count|)S%(playlist_autonumber& - |)S%(uploader,creator|UNKNOWN_AUTHOR)S %(release_date>%Y-%m-%d,upload_date>%Y-%m-%d|UNKNOWN_DATE)S - %(title|UNKNOWN_TITLE)S.%(ext)s'
      OUTPUT_TEMPLATE_PLAYLIST: '%(playlist_title&Playlist |)S%(playlist_title|)S%(playlist_uploader& by |)S%(playlist_uploader|)S%(playlist_autonumber& - |)S%(playlist_autonumber|)S%(playlist_count& of |)S%(playlist_count|)S%(playlist_autonumber& - |)S%(uploader,creator|UNKNOWN_AUTHOR)S %(release_date>%Y-%m-%d,upload_date>%Y-%m-%d|UNKNOWN_DATE)S - %(title|UNKNOWN_TITLE)S.%(ext)s'
      STATE_DIR: /data/state/
      TEMP_DIR: /data/temp/
      YTDL_OPTIONS: '{"writesubtitles":true,"subtitleslangs":["en","-live_chat"],"updatetime":false,"postprocessors":[{"key":"Exec","exec_cmd":"chmod 0664","when":"after_move"},{"key":"FFmpegEmbedSubtitle","already_have_subtitle":false},{"key":"FFmpegMetadata","add_chapters":true}]}'
    ports:
      - 8082:8081/tcp
    volumes:
      - ${USERPROFILE}\metube-data\:/data/:rw
      - E:\Downloads\YouTube\:/downloads/:rw

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Etc/UTC
    ports:
      - 9696:9696/tcp
    volumes:
      - ${USERPROFILE}\prowlarr-data\:/config/:rw

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Etc/UTC
      WEBUI_PORT: "8080"
      TORRENTING_PORT: "6881"
    ports:
      - 6881:6881/tcp
      - 6881:6881/udp
      - 8080:8080/tcp
    volumes:
      - ${USERPROFILE}\qbittorrent-data\:/config/:rw
      - E:\Downloads\:/downloads/:rw

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    ports:
      - 8083:8080/tcp
    volumes:
      - ${USERPROFILE}\sabnzbd-data\:/config/:rw
      - E:\Downloads\sabnzbd\:/config/Downloads/complete/:rw
      - E:\Downloads\sabnzbd\incomplete\:/config/Downloads/incomplete/:rw

  sickgear:
    image: sickgear/sickgear:latest
    ports:
      - 8081:8081/tcp
    volumes:
      - ${USERPROFILE}\sickgear-data\:/data/:rw
      - D:\anime\:/media/anime/:rw
      - D:\films\:/media/films/:rw
      - D:\Red-Letter Media\:/media/Red-Letter Media/:rw
      - D:\tvshows\:/media/tv/:rw
      - D:\videos\:/media/videos/:rw
      - E:\music\:/media/music/:rw
      - E:\pictures\:/media/pictures/:rw

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    ports:
      - 8989:8989/tcp
    volumes:
      - ${USERPROFILE}\sonarr-data\:/config/:rw
      - D:\tvshows\:/tv/:rw
      - E:\Downloads\sabnzbd\:/config/Downloads/complete/:rw
