---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- Monitoring:
    - ahti:
        href: https://glances-ahti.bob.house/
        icon: glances.png
        ping: ahti
        siteMonitor: https://glances-ahti.bob.house/api/4/status
        widget:
          type: prometheusmetric
          url: http://prometheus:9090
          refreshInterval: 10000 # optional - in milliseconds, defaults to 10s
          metrics:
            - label: user cpu
              format:
                type: percent
                options:
                  maximumFractionDigits: 1
                scale: 100
              query: rate(cpu_usage_user{host='ahti'}[5m])
            - label: system cpu
              format:
                type: percent
                options:
                  maximumFractionDigits: 1
                scale: 100
              query: rate(cpu_usage_system{host='ahti'}[5m])
            - label: D
              format:
                type: percent
                options:
                  maximumFractionDigits: 1
              query: disk_used_percent{host='ahti',path='\\D:'}
            - label: E
              format:
                type: percent
                options:
                  maximumFractionDigits: 1
              query: disk_used_percent{host='ahti',path='\\E:'}
    - marshall:
        href: https://glances-marshall.bob.house/
        icon: glances.png
        ping: marshall
        siteMonitor: https://glances-marshall.bob.house/api/4/status
        widget:
          type: prometheusmetric
          url: http://prometheus:9090
          refreshInterval: 10000 # optional - in milliseconds, defaults to 10s
          metrics:
            - label: user cpu
              format:
                type: percent
                options:
                  maximumFractionDigits: 1
                scale: 100
              query: rate(cpu_usage_user{host='marshall'}[5m])
            - label: system cpu
              format:
                type: percent
                options:
                  maximumFractionDigits: 1
                scale: 100
              query: rate(cpu_usage_system{host='marshall'}[5m])
            - label: free disk
              format:
                type: bytes
                options:
                  maximumFractionDigits: 1
              query: disk_free{host='marshall',path='\\C:'}
            - label: disk used
              format:
                type: percent
                options:
                  maximumFractionDigits: 1
              query: disk_used_percent{host='marshall',path='\\C:'}
    - pope:
        href: https://glances-pope.bob.house/
        icon: glances.png
        ping: pope
        siteMonitor: https://glances-pope.bob.house/api/4/status
        widget:
          type: prometheusmetric
          url: http://prometheus:9090
          refreshInterval: 10000 # optional - in milliseconds, defaults to 10s
          metrics:
            - label: user cpu
              format:
                type: percent
                options:
                  maximumFractionDigits: 1
                scale: 100
              query: rate(cpu_usage_user{host='pope'}[5m])
            - label: system cpu
              format:
                type: percent
                options:
                  maximumFractionDigits: 1
                scale: 100
              query: rate(cpu_usage_system{host='pope'}[5m])
            - label: free disk
              format:
                type: bytes
                options:
                  maximumFractionDigits: 1
              query: disk_free{host='pope',path='\\C:'}
            - label: disk used
              format:
                type: percent
                options:
                  maximumFractionDigits: 1
              query: disk_used_percent{host='pope',path='\\C:'}
    - trench:
        href: https://glances-trench.bob.house/
        icon: glances.png
        ping: host.docker.internal
        siteMonitor: https://glances-trench.bob.house/api/4/status
        widget:
          type: prometheusmetric
          url: http://prometheus:9090
          refreshInterval: 10000 # optional - in milliseconds, defaults to 10s
          metrics:
            - label: user cpu
              format:
                type: percent
                options:
                  maximumFractionDigits: 1
                scale: 100
              query: rate(cpu_usage_user{host='trench'}[5m])
            - label: system cpu
              format:
                type: percent
                options:
                  maximumFractionDigits: 1
                scale: 100
              query: rate(cpu_usage_system{host='trench'}[5m])
            - label: free disk
              format:
                type: bytes
                options:
                  maximumFractionDigits: 1
              query: disk_free{host='trench',path='\\C:'}
            - label: disk used
              format:
                type: percent
                options:
                  maximumFractionDigits: 1
              query: disk_used_percent{host='trench',path='\\C:'}

- Essentials:
    - Authentik:
        description: Bring all of your authentication into a unified platform
        href: https://authentik.bob.house
        icon: authentik.png
        ping: host.docker.internal
        siteMonitor: http://authentik-server:9000
        widget:
          type: authentik
          url: http://authentik-server:9000
          key: {{HOMEPAGE_VAR_AUTHENTIK_KEY}}
    - Dozzle:
        description: Real-time log viewer for docker containers
        href: https://dozzle.bob.house/
        icon: dozzle.svg
        ping: host.docker.internal
        siteMonitor: http://dozzle:8080/healthcheck
    - Frigate:
        description: NVR with realtime local object detection for IP cameras
        href: https://frigate.bob.house/
        icon: frigate.svg
        ping: marshall.fbc.local
        siteMonitor: http://marshall.fbc.local:5000
        widget:
          type: frigate
          url: http://marshall.fbc.local:5000
          enableRecentEvents: false
    - Home Assistant:
        description: Open-source home automation platform
        href: https://homeassistant.bob.house/
        icon: home-assistant.svg
        ping: host.docker.internal
        siteMonitor: http://homeassistant:8123
        widget:
          type: homeassistant
          url: http://homeassistant:8123
          key: {{HOMEPAGE_VAR_HOMEASSISTANT_KEY}}
          custom:
            - label: spotlight
              state: light.keylight
            - label: nanoleaf
              state: light.shapes_0324
            - label: bedroom
              state: light.bedroom_main
            - label: pc
              state: sensor.pc_current_consumption
    - Pi-hole:
        description: A blackhole for Internet advertisements
        href: https://pihole.bob.house/admin
        icon: pi-hole.svg
        ping: 192.168.1.80
        siteMonitor: https://pihole.bob.house/admin
        widget:
          type: pihole
          url: https://pihole.bob.house
          # version: 6 # required if running v6 or higher, defaults to 5
          key: {{HOMEPAGE_VAR_PIHOLE_KEY}} # optional
    - Portainer:
        description: Making Docker and Kubernetes management easy
        href: https://portainer.bob.house/
        icon: portainer.svg
        ping: host.docker.internal
        siteMonitor: http://portainer:9000
        widgets:
          - type: portainer
            url: http://portainer:9000
            env: 4
            key: {{HOMEPAGE_VAR_PORTAINER_KEY}}
          - type: portainer
            url: http://portainer:9000
            env: 5
            key: {{HOMEPAGE_VAR_PORTAINER_KEY}}
          - type: portainer
            url: http://portainer:9000
            env: 3
            key: {{HOMEPAGE_VAR_PORTAINER_KEY}}
          - type: portainer
            url: http://portainer:9000
            env: 2
            key: {{HOMEPAGE_VAR_PORTAINER_KEY}}
    - Prometheus:
        description: The Prometheus monitoring system and time series database
        href: https://prometheus.bob.house/
        icon: prometheus.svg
        ping: host.docker.internal
        siteMonitor: http://prometheus:9090
        widget:
          type: prometheus
          url: http://prometheus:9090
    - Traefik:
        description: HTTP reverse proxy and load balancer
        href: https://traefik.bob.house/dashboard/
        icon: traefik-proxy.svg
        ping: host.docker.internal
        siteMonitor: https://traefik.bob.house/dashboard/
        widget:
          type: traefik
          url: https://traefik.bob.house
    - Uptime Kuma:
        description: Self-hosted website monitoring tool
        href: https://uptimekuma.bob.house/dashboard/
        icon: uptime-kuma.svg
        ping: host.docker.internal
        siteMonitor: http://uptimekuma:3001/dashboard/
        widgets:
          - type: uptimekuma
            url: http://uptimekuma:3001
            slug: statuspageslug
          - type: uptimekuma
            url: http://uptimekuma:3001
            slug: iot

- Media Server:
    - Jellyfin:
        description: Your media, on your terms
        href: https://jellyfin.bob.house/web/
        icon: jellyfin.svg
        ping: ahti
        siteMonitor: https://jellyfin.bob.house/health
        widget:
          type: jellyfin
          url: https://jellyfin.bob.house
          key: {{HOMEPAGE_VAR_JELLYFIN_KEY}}
          enableBlocks: true # optional, defaults to false
          enableNowPlaying: true # optional, defaults to true
          enableUser: true # optional, defaults to false
          showEpisodeNumber: false # optional, defaults to false
          expandOneStreamToTwoRows: false # optional, defaults to true
    - Jellyseerr:
        description: Request management and media discovery tool for the Jellyfin ecosystem
        href: https://jellyseerr.bob.house/
        icon: jellyseerr.svg
        ping: ahti
        siteMonitor: https://jellyseerr.bob.house
        widget:
          type: jellyseerr
          url: https://jellyseerr.bob.house
          key: {{HOMEPAGE_VAR_JELLYSEERR_KEY}}
    - Lidarr:
        description: Looks and smells like Sonarr but made for music
        href: https://lidarr.bob.house/
        icon: lidarr.svg
        ping: ahti
        siteMonitor: https://lidarr.bob.house
        widget:
          type: lidarr
          url: https://lidarr.bob.house
          key: {{HOMEPAGE_VAR_LIDARR_KEY}}
    - MeTube:
        description: Web UI for youtube-dl / yt-dlp
        href: https://metube.bob.house/
        icon: metube.svg
        ping: ahti
        siteMonitor: https://metube.bob.house
    - Pinchflat:
        description: Your next YouTube media manager
        href: https://pinchflat.bob.house/
        icon: pinchflat.png
        ping: ahti
        siteMonitor: https://pinchflat.bob.house
    - Prowlarr:
        description: Indexer manager / proxy
        href: https://prowlarr.bob.house/
        icon: prowlarr.svg
        ping: ahti
        siteMonitor: https://prowlarr.bob.house
        widget:
          type: prowlarr
          url: https://prowlarr.bob.house
          key: {{HOMEPAGE_VAR_PROWLARR_KEY}}
    - qBittorrent:
        description: A BitTorrent client in Qt
        href: https://qbittorrent.bob.house
        icon: qbittorrent.svg
        ping: ahti
        siteMonitor: https://qbittorrent.bob.house
        widget:
          type: qbittorrent
          url: https://qbittorrent.bob.house
          username: {{HOMEPAGE_VAR_QBITTORRENT_USERNAME}}
          password: {{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}
    - Radarr:
        description: Movie organizer/manager for usenet and torrent users
        href: https://radarr.bob.house/
        icon: radarr.svg
        ping: ahti
        siteMonitor: https://radarr.bob.house
        widget:
          type: radarr
          url: https://radarr.bob.house
          key: {{HOMEPAGE_VAR_RADARR_KEY}}
          enableQueue: true # optional, defaults to false
    - SABnzbd:
        description: Free and easy binary newsreader
        href: https://sabnzbd.bob.house/
        icon: sabnzbd.svg
        ping: ahti
        siteMonitor: https://sabnzbd.bob.house
        widget:
          type: sabnzbd
          url: https://sabnzbd.bob.house
          key: {{HOMEPAGE_VAR_SABNZBD_KEY}}
    - Sick Gear:
        description: Fully automate TV enjoyment
        href: https://sickgear.bob.house/
        icon: sickbeard.svg
        ping: ahti
        siteMonitor: https://sickgear.bob.house
    - Sonarr:
        description: Usenet and BitTorrent PVR
        href: https://sonarr.bob.house/
        icon: sonarr.svg
        ping: ahti
        siteMonitor: https://sonarr.bob.house
        widget:
          type: sonarr
          url: https://sonarr.bob.house
          key: {{HOMEPAGE_VAR_SONARR_KEY}}
          enableQueue: true

- Services:
    - Change Detection:
        description: Web page change detection, website watcher, restock monitor and notification service
        href: https://changedetection.bob.house/
        icon: changedetection.svg
        ping: pope
        siteMonitor: http://pope:5000
        widget:
          type: changedetectionio
          url: http://pope:5000
          key: {{HOMEPAGE_VAR_CHANGEDETECTION_KEY}}
    - Docker Registry:
        description: UI for your private docker registry
        href: https://registry.bob.house/
        icon: docker-moby.svg
        ping: pope
        siteMonitor: http://pope:83
    - Donetick:
        description: Simplify Tasks & Chores, Together
        href: https://donetick.bob.house/
        icon: /icons/donetick.svg
        ping: pope
        siteMonitor: http://pope:2021
    - FreshRSS:
        description: A free, self-hostable news aggregator
        href: https://freshrss.bob.house/
        icon: freshrss.svg
        ping: pope
        siteMonitor: http://pope:80/i/
    - Grafana:
        description: The open and composable observability and data visualization platform
        href: https://grafana.bob.house/
        icon: grafana.svg
        ping: pope
        siteMonitor: http://pope:3000
        widget:
          type: grafana
          url: http://pope:3000
          username: {{HOMEPAGE_VAR_GRAFANA_USERNAME}}
          password: {{HOMEPAGE_VAR_GRAFANA_PASSWORD}}
    - hoarder:
        description: A self-hostable bookmark-everything app
        href: https://hoarder.bob.house/
        icon: hoarder-light.png
        ping: pope
        siteMonitor: http://pope:3004
    - httpbin:
        description: A simple HTTP Request & Response Service
        href: https://httpbin.bob.house/
        icon: /icons/httpbin.png
        ping: pope
        siteMonitor: http://pope:8081
    - IT-Tools:
        description: Collection of handy online tools for developers, with great UX
        href: https://it-tools.bob.house/
        icon: it-tools.svg
        ping: pope
        siteMonitor: http://pope:82
    - moodist:
        description: Ambient sounds for focus and calm
        href: https://moodist.bob.house/?share=%7B%22rain-on-window%22%3A0.07%2C%22crowd%22%3A0.59%2C%22inside-a-train%22%3A0.36%2C%22brown-noise%22%3A0.12%7D
        icon: /icons/moodist.svg
        ping: pope
        siteMonitor: http://pope:8082
    - n8n:
        description: Secure, AI-native workflow automation
        href: https://n8n.bob.house/
        icon: n8n.svg
        ping: pope
        siteMonitor: http://pope:5678
    - netboot.xyz:
        description: Your favourite operating systems in one place
        href: https://netboot.bob.house/
        icon: netboot.svg
        ping: pope
        siteMonitor: http://pope:3003
    - ntfy:
        description: Send push notifications to your phone or desktop via PUT/POST
        href: https://ntfy.bob.house/
        icon: ntfy.svg
        ping: pope
        siteMonitor: http://pope:27346
    - NuGet:
        description: A lightweight NuGet and symbol server
        href: https://nuget.bob.house/
        icon: microsoft.svg
        ping: pope
        siteMonitor: http://pope:8083/v3/index.json
    - Planka:
        description: Realtime kanban board for workgroups
        href: https://planka.bob.house/
        icon: planka.svg
        ping: pope
        siteMonitor: http://pope:1337
    - Speedtest:
        description: Free & Open-Source HTML5 Network Performance Estimation Tool
        href: https://speedtest.bob.house/
        icon: openspeedtest.png
        ping: pope
        siteMonitor: http://pope:84/api/healthcheck
    - Trilium:
        description: Hierarchical note taking application
        href: https://trilium.bob.house/
        icon: trilium.svg
        ping: pope
        siteMonitor: http://pope:8084/login
    - Vikunja:
        description: The to-do app to organize your life
        href: https://vikunja.bob.house/
        icon: vikunja.svg
        ping: pope
        siteMonitor: http://pope:3456
        widget:
          type: vikunja
          url: http://pope:3456
          key: {{HOMEPAGE_VAR_VIKUNJA_KEY}}
          enableTaskList: true
    - What's Up Docker:
        description: Gets you notified when a new version of your Docker Container is available
        href: https://whatsupdocker.bob.house/
        icon: whats-up-docker.svg
        ping: pope
        siteMonitor: http://pope:3002
        widget:
          type: whatsupdocker
          url: http://pope:3002
