---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings

background: /images/control.png

cardBlur: sm # sm, "", md, etc... see https://tailwindcss.com/docs/backdrop-blur

color: zinc # amber, blue, cyan, emerald, fuchsia, gray, green, indigo, lime, neutral, pink, purple, red, rose, sky, slate, stone, teal, violet, white, yellow, zinc

disableCollapse: true

headerStyle: boxed

layout:
  Developer:
  Social:
  Entertainment:
  Monitoring:
    columns: 2
    style: row
  Essentials:
    columns: 4
    style: row
  Media Server:
    columns: 4
    style: row
    fiveColumns: true
  Services:
    columns: 4
    style: row
  Network:
    columns: 2
    style: row

providers:
  finnhub: {{HOMEPAGE_VAR_PROVIDERS_FINNHUB}}
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

statusStyle: "dot"
