---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- monitoring:
    - ahti:
        href: https://glances-ahti/
        icon: glances.png
        ping: glances-ahti
        siteMonitor: https://glances-ahti/api/4/status
    - marshall:
        href: https://glances-marshall/
        icon: glances.png
        ping: glances-marshall
        siteMonitor: https://glances-marshall/api/4/status
    - pope:
        href: https://glances-pope/
        icon: glances.png
        ping: glances-pope
        siteMonitor: https://glances-pope/api/4/status
    - ahti cpu:
        widget:
          type: glances
          metric: cpu
          pointsLimit: 100
          refreshInterval: 3000
          url: https://glances-ahti
          version: 4
    - marshall cpu:
        widget:
          type: glances
          metric: cpu
          pointsLimit: 100
          refreshInterval: 3000
          url: https://glances-marshall
          version: 4
    - pope cpu:
        widget:
          type: glances
          metric: cpu
          pointsLimit: 100
          refreshInterval: 3000
          url: https://glances-pope
          version: 4
    - ahti eth0:
        widget:
          type: glances
          metric: network:eth0
          pointsLimit: 100
          refreshInterval: 3000
          url: https://glances-ahti
          version: 4
    - marshall eth0:
        widget:
          type: glances
          metric: network:eth0
          pointsLimit: 100
          refreshInterval: 3000
          url: https://glances-marshall
          version: 4
    - pope eth0:
        widget:
          type: glances
          metric: network:eth0
          pointsLimit: 100
          refreshInterval: 3000
          url: https://glances-pope
          version: 4

- Media Server:
    - Jellyfin:
        href: https://jellyfin/web/
        icon: jellyfin.svg
        ping: ahti
        siteMonitor: https://jellyfin/health
        widget:
          type: jellyfin
          url: https://jellyfin
          key: 8c70503628304809803c593fa339b921
          enableBlocks: true # optional, defaults to false
          enableNowPlaying: true # optional, defaults to true
          enableUser: true # optional, defaults to false
          # showEpisodeNumber: true # optional, defaults to false
          expandOneStreamToTwoRows: false # optional, defaults to true
    - MeTube:
        href: https://metube/
        icon: metube.svg
        ping: ahti
        siteMonitor: https://metube
    - Prowlarr:
        href: https://prowlarr/
        icon: prowlarr.svg
        ping: prowlarr
        siteMonitor: https://prowlarr
        widget:
          type: prowlarr
          url: https://prowlarr
          key: 8fb67584ab6f42b09e02d93fd3f0e1d3
    - qBittorrent:
        href: https://qbittorrent
        icon: qbittorrent.svg
        ping: ahti
        siteMonitor: https://qbittorrent
        widget:
          type: qbittorrent
          url: https://qbittorrent
          username: admin
          password: password
    - SABnzbd:
        href: https://sabnzbd/
        icon: sabnzbd-alt.svg
        ping: ahti
        siteMonitor: https://sabnzbd
        widget:
          type: sabnzbd
          url: https://sabnzbd
          key: 5949065fc49247269b110d8ce426e195
    - Sick Gear:
        href: https://sickgear/
        icon: sickbeard.svg
        ping: ahti
        siteMonitor: https://sickgear
    - Sonarr:
        href: https://sonarr/
        icon: sonarr.svg
        ping: sonarr
        siteMonitor: https://sonarr
        widget:
          type: sonarr
          url: https://sonarr
          key: 26b7b613fbed470eaa2b273997c94938
          enableQueue: true

- Services:
    - Change Detection:
        href: https://changedetection/
        icon: changedetection-io.png
        ping: changedetection
        siteMonitor: http://changedetection:5000
        widget:
          type: changedetectionio
          url: http://changedetection:5000
          key: b907fb20b376747d27db01e8e4056ce7
    - Docker Registry:
        href: https://registry/
        icon: docker-moby.svg
        ping: registry
        siteMonitor: http://registry:5000/v2/_catalog
    - Frigate:
        href: https://frigate/
        icon: frigate.svg
        ping: marshall
        siteMonitor: https://frigate
        widget:
          type: frigate
          url: https://frigate
          enableRecentEvents: true
    - Home Assistant:
        href: https://homeassistant/
        icon: home-assistant.svg
        ping: homeassistant
        siteMonitor: http://homeassistant:8123
        widget:
          type: homeassistant
          url: http://homeassistant:8123
          key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI3ZDZiOTUyYzYyOWU0ZDliYjFhMDVhMDMwYTAxOTdkNCIsImlhdCI6MTcyODkxODM0NywiZXhwIjoyMDQ0Mjc4MzQ3fQ.1jiQ_KHIzSI60IXJSJPYv6MOGahpinzaempeW__lLi4
          custom:
            - label: spotlight
              state: light.keylight
            - label: nanoleaf
              state: light.shapes_0324
            - label: bedroom
              state: light.bedroom_main
            - label: pc
              state: sensor.pc_current_consumption
    - httpbin:
        href: https://httpbin/
        icon: /icons/httpbin.png
        ping: httpbin
        siteMonitor: http://httpbin:8080
    - moodist:
        href: https://moodist/?share=%7B%22rain-on-window%22%3A0.07%2C%22crowd%22%3A0.59%2C%22inside-a-train%22%3A0.36%2C%22brown-noise%22%3A0.12%7D
        icon: /icons/moodist.svg
        ping: moodist
        siteMonitor: http://moodist:8080
    - ntfy:
        href: https://ntfy/
        icon: ntfy-light.png
        ping: ntfy
        siteMonitor: http://ntfy
    - NuGet:
        href: https://nuget/
        icon: microsoft.svg
        ping: nuget
        siteMonitor: http://nuget:8080/v3/index.json
    - Pi-hole:
        href: https://pihole/admin
        icon: pi-hole.svg
        ping: pihole
        siteMonitor: https://pihole/admin
        widget:
          type: pihole
          url: https://pihole
          # version: 6 # required if running v6 or higher, defaults to 5
          key: 3e8964b5fabacdb7cb983a50c7d92f4fc80a52f9d9875ae6ac2dbeab5ee134b9 # optional
    - Planka:
        href: https://planka/
        icon: planka.svg
        ping: planka
        siteMonitor: http://planka:1337
    - Speedtest:
        href: https://speedtest/
        icon: openspeedtest.png
        ping: speedtest-tracker
        siteMonitor: http://speedtest-tracker/api/healthcheck
    - Traefik:
        href: https://traefik/dashboard/
        icon: traefik-proxy.svg
        ping: traefik
        siteMonitor: https://traefik/dashboard/
        widget:
          type: traefik
          url: https://traefik
    - Trilium:
        href: https://trilium/
        icon: trilium.svg
        ping: trilium
        siteMonitor: http://trilium:8080/login
    - Uptime Kuma:
        href: https://uptimekuma/dashboard/
        icon: uptime-kuma.svg
        ping: uptimekuma
        siteMonitor: http://uptimekuma:3001/dashboard/
        widget:
          type: uptimekuma
          url: http:///uptimekuma:3001
          slug: statuspageslug
    - Uptime Kuma (Work):
        href: https://uptimekuma/dashboard/
        icon: uptime-kuma.svg
        ping: http://uptimekuma
        siteMonitor: http://uptimekuma:3001/dashboard/
        widget:
          type: uptimekuma
          url: http:///uptimekuma:3001
          slug: work
    - Vikunja:
        href: https://vikunja/
        icon: vikunja.svg
        ping: vikunja
        siteMonitor: http://vikunja:3456
        widget:
          type: vikunja
          url: http://vikunja:3456
          key: tk_a44cad21abd01102306dd754bc9527ef01b8b0cc
          enableTaskList: true
    - What's Up Docker:
        href: https://whatsupdocker/
        icon: whats-up-docker.svg
        ping: whatsupdocker
        siteMonitor: http://whatsupdocker:3000
        widget:
          type: whatsupdocker
          url: http://whatsupdocker:3000
