---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- monitoring:
    - ahti:
        href: https://glances-ahti/
        icon: glances.png
        ping: ahti
        siteMonitor: https://glances-ahti/api/4/status
        widget:
          type: prometheusmetric
          url: http://prometheus:9090
          refreshInterval: 10000 # optional - in milliseconds, defaults to 10s
          metrics:
            - label: user cpu
              format:
                type: percent
                options:
                  maximumFractionDigits: 1
                scale: 100
              query: rate(cpu_usage_user{host='ahti'}[5m])
            - label: system cpu
              format:
                type: percent
                options:
                  maximumFractionDigits: 1
                scale: 100
              query: rate(cpu_usage_system{host='ahti'}[5m])
            - label: D
              format:
                type: percent
                options:
                  maximumFractionDigits: 1
              query: disk_used_percent{host='ahti',path='\\D:'}
            - label: E
              format:
                type: percent
                options:
                  maximumFractionDigits: 1
              query: disk_used_percent{host='ahti',path='\\E:'}
    - marshall:
        href: https://glances-marshall/
        icon: glances.png
        ping: marshall
        siteMonitor: https://glances-marshall/api/4/status
        widget:
          type: prometheusmetric
          url: http://prometheus:9090
          refreshInterval: 10000 # optional - in milliseconds, defaults to 10s
          metrics:
            - label: user cpu
              format:
                type: percent
                options:
                  maximumFractionDigits: 1
                scale: 100
              query: rate(cpu_usage_user{host='marshall'}[5m])
            - label: system cpu
              format:
                type: percent
                options:
                  maximumFractionDigits: 1
                scale: 100
              query: rate(cpu_usage_system{host='marshall'}[5m])
            - label: free disk
              format:
                type: bytes
                options:
                  maximumFractionDigits: 1
              query: disk_free{host='marshall',path='/'}
            - label: disk used
              format:
                type: percent
                options:
                  maximumFractionDigits: 1
              query: disk_used_percent{host='marshall',path='/'}
    - pope:
        href: https://glances-pope/
        icon: glances.png
        ping: host.docker.internal
        siteMonitor: https://glances-pope/api/4/status
        widget:
          type: prometheusmetric
          url: http://prometheus:9090
          refreshInterval: 10000 # optional - in milliseconds, defaults to 10s
          metrics:
            - label: user cpu
              format:
                type: percent
                options:
                  maximumFractionDigits: 1
                scale: 100
              query: rate(cpu_usage_user{host='pope'}[5m])
            - label: system cpu
              format:
                type: percent
                options:
                  maximumFractionDigits: 1
                scale: 100
              query: rate(cpu_usage_system{host='pope'}[5m])
            - label: free disk
              format:
                type: bytes
                options:
                  maximumFractionDigits: 1
              query: disk_free{host='pope',path='\\C:'}
            - label: disk used
              format:
                type: percent
                options:
                  maximumFractionDigits: 1
              query: disk_used_percent{host='pope',path='\\C:'}

- Media Server:
    - Jellyfin:
        description: Your media, on your terms
        href: https://jellyfin/web/
        icon: jellyfin.svg
        ping: ahti
        siteMonitor: https://jellyfin/health
        widget:
          type: jellyfin
          url: https://jellyfin
          key: 5fe7b340a49c445e85c028594fa7e57e
          enableBlocks: true # optional, defaults to false
          enableNowPlaying: true # optional, defaults to true
          enableUser: true # optional, defaults to false
          showEpisodeNumber: false # optional, defaults to false
          expandOneStreamToTwoRows: false # optional, defaults to true
    - Jellyseerr:
        description: Request management and media discovery tool for the Jellyfin ecosystem
        href: https://jellyseerr/
        icon: jellyseerr.svg
        ping: ahti
        siteMonitor: https://jellyseerr
        widget:
          type: jellyseerr
          url: https://jellyseerr
          key: MTczMTgzMzY3MDAxMThlNGE3N2EwLWQ2NWItNDgxNi04Y2VjLWE1YzAzN2FkMjc4NQ==
    - Lidarr:
        description: Looks and smells like Sonarr but made for music
        href: https://lidarr/
        icon: lidarr.svg
        ping: ahti
        siteMonitor: https://lidarr
        widget:
          type: lidarr
          url: https://lidarr
          key: 660391ff2d8d478ea0b95c9330745daf
    - MeTube:
        description: Web UI for youtube-dl / yt-dlp
        href: https://metube/
        icon: metube.svg
        ping: ahti
        siteMonitor: https://metube
    - Prowlarr:
        description: Indexer manager / proxy
        href: https://prowlarr/
        icon: prowlarr.svg
        ping: ahti
        siteMonitor: https://prowlarr
        widget:
          type: prowlarr
          url: https://prowlarr
          key: 8fb67584ab6f42b09e02d93fd3f0e1d3
    - qBittorrent:
        description: A BitTorrent client in Qt
        href: https://qbittorrent
        icon: qbittorrent.svg
        ping: ahti
        siteMonitor: https://qbittorrent
        widget:
          type: qbittorrent
          url: https://qbittorrent
          username: admin
          password: password
    - Radarr:
        description: Movie organizer/manager for usenet and torrent users
        href: https://radarr/
        icon: radarr-light.png
        ping: ahti
        siteMonitor: https://radarr
        widget:
          type: radarr
          url: https://radarr
          key: 5f8d3784c8c54ff6b49c3b6f4700d649
          enableQueue: true # optional, defaults to false
    - SABnzbd:
        description: Free and easy binary newsreader
        href: https://sabnzbd/
        icon: sabnzbd-alt.svg
        ping: ahti
        siteMonitor: https://sabnzbd
        widget:
          type: sabnzbd
          url: https://sabnzbd
          key: 5949065fc49247269b110d8ce426e195
    - Sick Gear:
        description: Fully automate TV enjoyment
        href: https://sickgear/
        icon: sickbeard.svg
        ping: ahti
        siteMonitor: https://sickgear
    - Sonarr:
        description: Usenet and BitTorrent PVR
        href: https://sonarr/
        icon: sonarr.svg
        ping: ahti
        siteMonitor: https://sonarr
        widget:
          type: sonarr
          url: https://sonarr
          key: 26b7b613fbed470eaa2b273997c94938
          enableQueue: true
    - Tube Archivist:
        description: Your self hosted YouTube media server
        href: https://tubearchivist/
        icon: tube-archivist.png
        ping: ahti
        siteMonitor: https://tubearchivist/health
        widget:
          type: tubearchivist
          url: https://tubearchivist
          key: 7d1f478d86cd99b39a8f0e6ed1fd2b626bb1aa45

- Services:
    - Change Detection:
        description: Web page change detection, website watcher, restock monitor and notification service
        href: https://changedetection/
        icon: changedetection-io.png
        ping: host.docker.internal
        siteMonitor: http://changedetection:5000
        widget:
          type: changedetectionio
          url: http://changedetection:5000
          key: b907fb20b376747d27db01e8e4056ce7
    - Docker Registry:
        description: UI for your private docker registry
        href: https://registry/
        icon: docker-moby.svg
        ping: host.docker.internal
        siteMonitor: http://registry:5000/v2/_catalog
    - Dozzle:
        description: Real-time log viewer for docker containers
        href: https://dozzle/
        icon: dozzle.svg
        ping: host.docker.internal
        siteMonitor: http://dozzle:8080/healthcheck
    - FreshRSS:
        description: A free, self-hostable news aggregator
        href: https://freshrss/
        icon: freshrss.svg
        ping: host.docker.internal
        siteMonitor: http://freshrss/i/
        widget:
          type: freshrss
          url: http://freshrss
          username: df208eb1b2ee8171
          password: f79376b034765b37cc1c97404ab035846167cd9a2e7924e60116aeec0e04a55c
    - Frigate:
        description: NVR with realtime local object detection for IP cameras
        href: https://frigate/
        icon: frigate.svg
        ping: marshall
        siteMonitor: https://frigate
        widget:
          type: frigate
          url: https://frigate
          enableRecentEvents: true
    - Grafana:
        description: The open and composable observability and data visualization platform
        href: https://grafana/
        icon: grafana.svg
        ping: host.docker.internal
        siteMonitor: http://grafana:3000
        widget:
          type: grafana
          url: http://grafana:3000
          username: admin
          password: 06daab76a3828eddf82ad342c9cdf1a7
    - Home Assistant:
        description: Open-source home automation platform
        href: https://homeassistant/
        icon: home-assistant.svg
        ping: host.docker.internal
        siteMonitor: http://homeassistant:8123
        widget:
          type: homeassistant
          url: http://homeassistant:8123
          key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI3ZDZiOTUyYzYyOWU0ZDliYjFhMDVhMDMwYTAxOTdkNCIsImlhdCI6MTcyODkxODM0NywiZXhwIjoyMDQ0Mjc4MzQ3fQ.1jiQ_KHIzSI60IXJSJPYv6MOGahpinzaempeW__lLi4
          custom:
            - label: spotlight
              state: light.keylight
            - label: nanoleaf
              state: light.shapes_0324
            - label: bedroom
              state: light.bedroom_main
            - label: pc
              state: sensor.pc_current_consumption
    - httpbin:
        description: A simple HTTP Request & Response Service
        href: https://httpbin/
        icon: /icons/httpbin.png
        ping: host.docker.internal
        siteMonitor: http://httpbin:8080
    - IT-Tools:
        description: Collection of handy online tools for developers, with great UX
        href: https://it-tools/
        icon: it-tools.svg
        ping: host.docker.internal
        siteMonitor: http://it-tools
    - moodist:
        description: Ambient sounds for focus and calm
        href: https://moodist/?share=%7B%22rain-on-window%22%3A0.07%2C%22crowd%22%3A0.59%2C%22inside-a-train%22%3A0.36%2C%22brown-noise%22%3A0.12%7D
        icon: /icons/moodist.svg
        ping: host.docker.internal
        siteMonitor: http://moodist:8080
    - ntfy:
        description: Send push notifications to your phone or desktop via PUT/POST
        href: https://ntfy/
        icon: ntfy-light.png
        ping: host.docker.internal
        siteMonitor: http://ntfy
    - NuGet:
        description: A lightweight NuGet and symbol server
        href: https://nuget/
        icon: microsoft.svg
        ping: host.docker.internal
        siteMonitor: http://nuget:8080/v3/index.json
    - Pi-hole:
        description: A blackhole for Internet advertisements
        href: https://pihole/admin
        icon: pi-hole.svg
        ping: 192.168.1.80
        siteMonitor: https://pihole/admin
        widget:
          type: pihole
          url: https://pihole
          # version: 6 # required if running v6 or higher, defaults to 5
          key: 3e8964b5fabacdb7cb983a50c7d92f4fc80a52f9d9875ae6ac2dbeab5ee134b9 # optional
    - Planka:
        description: Realtime kanban board for workgroups
        href: https://planka/
        icon: planka.svg
        ping: host.docker.internal
        siteMonitor: http://planka:1337
    - Prometheus:
        description: The Prometheus monitoring system and time series database
        href: https://prometheus/
        icon: prometheus.svg
        ping: host.docker.internal
        siteMonitor: http://prometheus:9090
        widget:
          type: prometheus
          url: http://prometheus:9090
    - Speedtest:
        description: Free & Open-Source HTML5 Network Performance Estimation Tool
        href: https://speedtest/
        icon: openspeedtest.png
        ping: host.docker.internal
        siteMonitor: http://speedtest-tracker/api/healthcheck
    - Traefik:
        description: HTTP reverse proxy and load balancer
        href: https://traefik/dashboard/
        icon: traefik-proxy.svg
        ping: host.docker.internal
        siteMonitor: https://traefik/dashboard/
        widget:
          type: traefik
          url: https://traefik
    - Trilium:
        description: Hierarchical note taking application
        href: https://trilium/
        icon: trilium.svg
        ping: host.docker.internal
        siteMonitor: http://trilium:8080/login
    - Uptime Kuma:
        description: Self-hosted website monitoring tool
        href: https://uptimekuma/dashboard/
        icon: uptime-kuma.svg
        ping: host.docker.internal
        siteMonitor: http://uptimekuma:3001/dashboard/
        widget:
          type: uptimekuma
          url: http:///uptimekuma:3001
          slug: statuspageslug
    - Uptime Kuma (Work):
        description: Self-hosted website monitoring tool
        href: https://uptimekuma/dashboard/
        icon: uptime-kuma.svg
        ping: host.docker.internal
        siteMonitor: http://uptimekuma:3001/dashboard/
        widget:
          type: uptimekuma
          url: http:///uptimekuma:3001
          slug: work
    - Vikunja:
        description: The to-do app to organize your life
        href: https://vikunja/
        icon: vikunja.svg
        ping: host.docker.internal
        siteMonitor: http://vikunja:3456
        widget:
          type: vikunja
          url: http://vikunja:3456
          key: tk_a44cad21abd01102306dd754bc9527ef01b8b0cc
          enableTaskList: true
    - What's Up Docker:
        description: Gets you notified when a new version of your Docker Container is available
        href: https://whatsupdocker/
        icon: whats-up-docker.svg
        ping: host.docker.internal
        siteMonitor: http://whatsupdocker:3000
        widget:
          type: whatsupdocker
          url: http://whatsupdocker:3000
