endpoints:
  - name: billups
    group: traefik
    url: https://192.168.1.75/dashboard/
    client: &client-definition
      insecure: true
      ignore-redirect: true
      timeout: 1s
    headers:
      Host: traefik-billups.bob.house
    conditions: &conditions-definition
      - "[RESPONSE_TIME] < 50"
      - "[STATUS] == 200"
    alerts: &alerts-definition
      - type: ntfy

  - name: freeman
    group: traefik
    url: https://192.168.20.60/dashboard/
    client: *client-definition
    headers:
      Host: traefik.bob.house
    conditions: *conditions-definition
    alerts: *alerts-definition

  - name: ransom
    group: traefik
    url: https://192.168.20.65/dashboard/
    client: *client-definition
    headers:
      Host: traefik-ransom.bob.house
    conditions: *conditions-definition
    alerts: *alerts-definition

  - name: shaxs
    group: traefik
    url: https://192.168.20.55/dashboard/
    client: *client-definition
    headers:
      Host: traefik-shaxs.bob.house
    conditions: *conditions-definition
    alerts: *alerts-definition

  - name: tana
    group: traefik
    url: https://192.168.20.70/dashboard/
    client: *client-definition
    headers:
      Host: traefik-tana.bob.house
    conditions: *conditions-definition
    alerts: *alerts-definition
