http:
  routers:
    frigate-router:
      entryPoints:
        - "websecure"
      rule: "Host(`frigate`)"
      service: "frigate-service"
      tls: "true"
    glances-ahti-router:
      entryPoints:
        - "websecure"
      rule: "Host(`glances-ahti`)"
      service: "glances-ahti-service"
      tls: "true"
    glances-marshall-router:
      entryPoints:
        - "websecure"
      rule: "Host(`glances-marshall`)"
      service: "glances-marshall-service"
      tls: "true"
    jellyfin-router:
      entryPoints:
        - "websecure"
      rule: "Host(`jellyfin`)"
      service: "jellyfin-service"
      tls: "true"
    metube-router:
      entryPoints:
        - "websecure"
      rule: "Host(`metube`)"
      service: "metube-service"
      tls: "true"
    pihole-router:
      entryPoints:
        - "websecure"
      rule: "Host(`pihole`)"
      service: "pihole-service"
      tls: "true"
    prowlarr-router:
      entryPoints:
        - "websecure"
      rule: "Host(`prowlarr`)"
      service: "prowlarr-service"
      tls: "true"
    qbittorrent-router:
      entryPoints:
        - "websecure"
      rule: "Host(`qbittorrent`)"
      service: "qbittorrent-service"
      tls: "true"
    router1-router:
      entryPoints:
        - "websecure"
      rule: "Host(`router1`)"
      service: "router1-service"
      tls: "true"
    sickgear-router:
      entryPoints:
        - "websecure"
      rule: "Host(`sickgear`)"
      service: "sickgear-service"
      tls: "true"
    sabnzbd-router:
      entryPoints:
        - "websecure"
      rule: "Host(`sabnzbd`)"
      service: "sabnzbd-service"
      tls: "true"
    sonarr-router:
      entryPoints:
        - "websecure"
      rule: "Host(`sonarr`)"
      service: "sonarr-service"
      tls: "true"
  services:
    frigate-service:
      loadBalancer:
        servers:
        - url: "http://marshall:5000/"
    glances-ahti-service:
      loadBalancer:
        servers:
        - url: "http://ahti:61208/"
    glances-marshall-service:
      loadBalancer:
        servers:
        - url: "http://marshall:61208/"
    jellyfin-service:
      loadBalancer:
        servers:
        - url: "http://ahti:8096/"
    metube-service:
      loadBalancer:
        servers:
        - url: "http://ahti:8082/"
    pihole-service:
      loadBalancer:
        servers:
        - url: "http://192.168.1.80"
    prowlarr-service:
      loadBalancer:
        servers:
        - url: "http://ahti:9696/"
    qbittorrent-service:
      loadBalancer:
        servers:
        - url: "http://ahti:8080/"
    router1-service:
      loadBalancer:
        servers:
        - url: "http://192.168.1.10"
    sabnzbd-service:
      loadBalancer:
        servers:
        - url: "http://ahti:8083/"
    sickgear-service:
      loadBalancer:
        servers:
        - url: "http://ahti:8081/"
    sonarr-service:
      loadBalancer:
        servers:
        - url: "http://ahti:8989/"

tls:
  certificates:
    - certFile: /etc/certs/localhost.crt
      keyFile: /etc/certs/localhost.key
